### ISSUE TITLE
Push to Gerrit

### ISSUE THREAD

**Issue by keedon** [Harvey-OS/harvey#1]
Hi,

I tried to push to gerrit, not a particularly complicated change, I just fixed some warnings, but it keeps getting rejected with:

 ! [remote rejected] HEAD -> refs/for/master (not Signed-off-by author/committer/uploader in commit message footer)

What am I missing?

Keith

**Comment by elbing** [comment]
Please, go to our mailing list and post this issue. There we got you standard gerrit instructions to use it. 
https://groups.google.com/forum/?hl=es#!forum/harvey

Thanks and welcome!

**Comment by elbing** [comment]
I added Everyone from github to read and push, so it should be allow you to push.

Thanks again, don't forget to come to our google groups.

**Comment by wwaites** [comment]
I similarly have a minor patch, which is not possible to push because of permissions.
I created an account on gerrithub.io and followed the instructions in the README file. 
In particular, I see,

    remote: Resolving deltas: 100% (3/3)
    remote: Processing changes: refs: 1, done    
    To ssh://wwaites@review.gerrithub.io:29418/elbing/harvey
     ! [remote rejected] HEAD -> refs/for/master (project is read only)
    error: failed to push some refs to 'ssh://wwaites@review.gerrithub.io:29418/elbing/harvey'

when I try to push my change.

Unfortunately I do not have an active Google account and so cannot usefully join the group.

**Comment by elbing** [comment]
Again,  please, this is not attended. Come to our Google group. See our wiki, be sure that you have right repo (harvey-os/harvey). We need to fix wiki. You're welcome.
Thanks!

**Comment by wwaites** [comment]
Sorted! The information in the README (which is the first thing that
people like me read when visiting the github page) is out of
date. I've pushed a patch.

**Comment by rminnich** [comment]
I think this is fixed. And I get to close our first issue!
