### ISSUE TITLE
Link to mailing list is broken

### ISSUE THREAD

**Issue by ct1n** [Harvey-OS/harvey#1017]
Both https://harvey-os.org/community/ and https://github.com/Harvey-OS/harvey/wiki link to a Google group as the mailing list:
http://groups.google.com/forum/#!forum/harvey

Visiting that link results in "Content unavailable". Tried a couple of Google accounts, same result.

**Comment by sevki** [comment]
![image](https://user-images.githubusercontent.com/429977/95199669-195ebe00-07d5-11eb-8be2-d71cc40f4621.png)

![image](https://user-images.githubusercontent.com/429977/95200100-bc173c80-07d5-11eb-8c1b-35b0a50408b2.png)

**Comment by ct1n** [comment]
Have you tried an incognito page, without being signed in?

Could you check the group permissions?
https://support.google.com/groups/answer/2464975?hl=en

**Comment by sevki** [comment]
To be honest it's not used at all, so we should probably remove the links to it. Slack is where it's at! harvey-os.slack.com/
