### ISSUE TITLE
After running Harvey with the script compilating Harvey fails

### ISSUE THREAD

**Issue by grd** [Harvey-OS/harvey#104]
#### Expected behavior

Compilation without errors.

#### Actual behavior

Compilation errors with:
`2016/03/23 21:01:08 "mksys -o sys.h '-mode=sys.h' $HARVEY/sys/src/sysconf.json " | /bin/sh`
`/bin/sh: 1: mksys: not found`

I think that setting the HARVEY environment variable is the problem. (On Linux)

**Comment by sevki** [comment]
would you please provide steps to reproduce @grd, because I'm certain you are missing some environment variables, mainly in $PATH. another option is that you might have forgot to ./bootstrap but I don't think that's likely

**Comment by grd** [comment]
Steps to reproduce:

`./bootstrap.sh'
`export ARCH=amd64`
`./util/build` // it compiles
`export HARVEY=~/harvey`
`cd ~/harvey/sys/src/9/amd64`
`sh ../../../../util/GO9PRUN`
`./util/build` // it errors

**Comment by rminnich** [comment]
**// it errors**
what errors? There's not enough info here.
do this
script /tmp/fail
do all these commands
^D
Paste the output here.

**Comment by grd** [comment]
See this output file: [output.txt](https://github.com/Harvey-OS/harvey/files/186782/output.txt)

**Comment by sevki** [comment]
@grd you are missing the `$GOBIN` set in `./bootstrap` in your `$PATH`

can you please paste the output of `printenv`?

**Comment by rminnich** [comment]
which mksys

There's your answer.

**Comment by elbing** [comment]
I consider this solved.
