### ISSUE TITLE
What is the reason to use GPL?

### ISSUE THREAD

**Issue by dcand** [Harvey-OS/harvey#1040]

**Comment by orangecms** [comment]
There are other Plan 9 systems under different licenses. We sought to have one under GPL, which is part of the purpose of the project. Does that answer your question? Maybe we can add that to the website. :)

**Comment by dcand** [comment]
> which is part of the purpose of the project

what is the purpose? Does using an BSD/MIT/ISC license violets the purpose?

**Comment by orangecms** [comment]
Sorry, I think we are heading a bit in a wrong direction. Let's start over. Could you elaborate on your question? I.e., do you seek to use Harvey for something that would violate the license?
