### ISSUE TITLE
Add devdc() and devname() functions to all dev*.c

### ISSUE THREAD

**Issue by rminnich** [Harvey-OS/harvey#1058]
All dev*.c files should have these two functions
static char *
devname(void)
{
        return devtab.name;
}

static int
devdc(void)
{
        return devtab.dc;
}

That way, we avoid problems like the recent breakage with devregress.c where in the devtab we used 'R' but in the attach we use 'Z', which collided with devacpi

Good beginner issue. It might be a simple awk/sed script. For bonus points, use spatch.

**Comment by michiboo** [comment]
Hi can I help on this issue?

**Comment by gmacd** [comment]
Sorry for the delay @michiboo - any help is always appreciated!
