### ISSUE TITLE
Add the build time to the boot info

### ISSUE THREAD

**Issue by floren** [Harvey-OS/harvey#1069]
When the kernel first starts, when it prints "Harvey\n" it should ALSO print the date/time when the kernel was built and the commit ID.

This will help in debugging, making sure you're up-to-date.

**Comment by kc101010** [comment]
Hello! New to open source! Could I be assigned this issue to work on? Thanks!

**Comment by sevki** [comment]
Hi and welcome! 

We don't really assign issues to people but please feel free to send a pr!
