### ISSUE TITLE
attempting to build harvey fails because there is no syslinux script in the utils folder

### ISSUE THREAD

**Issue by Lexi-kelly** [Harvey-OS/harvey#1072]
#### Expected behavior
it builds successfully
#### Actual behavior
"-bash: ./syslinux: No such file or directory"
#### Steps to reproduce
- open a terminal on ubuntu 18.04 and do sudo -i then run all commands as root
- follow getting started and building harvey exactly as it says
- skip running on qemu
- follow creating harvey image exactly
- watch it fail

#### QEMU output
<details>
```
<your output here>
```
</details>

**Comment by fhs** [comment]
I'm guessing you're following the instructions here: https://github.com/Harvey-OS/harvey/wiki/Booting-Harvey-on-real-hardware-II-(USB) ?
These instructions don't get tested often as most of us netboot harvey these days.

The `syslinux` command is a Go program that's installed from [harvey-os.org/cmd/syslinux](https://pkg.go.dev/harvey-os.org/cmd/syslinux) into `$HARVEY/linux_amd64/bin`. It works if you run it from `util` directory, but we need to fix both the wiki instructions and how syslinux works.

**Comment by Lexi-kelly** [comment]
yes I was following those instructions, if I installed the syslinux Go program would i then be able to build a bootable harvey USB?

**Comment by fhs** [comment]
@Lexi-kelly I think that syslinux program should be deleted. Try the `util/build-img.sh` script instead from PR #1076.

**Comment by Lexi-kelly** [comment]
doesn't the build-img script only build a qemu image? i'm looking to make a bootable usb image, is there a way i could change the script to do that or convert the qemu image to a bootable usb?

**Comment by fhs** [comment]
@Lexi-kelly If you run `./util/build-img.sh -f raw` it'll produce a raw image instead of a qcow2. Then you can copy it to your usb stick.

**Comment by Lexi-kelly** [comment]
thank you for your help with this issue. I was just a bit confused due to the documentation mentioning the syslinux script, i'm guessing the build-img script is basically the same as the syslinux script just with a different name?

**Comment by fhs** [comment]
> thank you for your help with this issue. I was just a bit confused due to the documentation mentioning the syslinux script, i'm guessing the build-img script is basically the same as the syslinux script just with a different name?

Yeah, they do pretty much the same thing as far as I understand but implemented very differently. The `build-img.sh` script uses guestfish which mean it doesn't require root access and it'll also more portable since it doesn't depend on linux kernel's nbd module.
