### ISSUE TITLE
building Harvey-OS succeeds, but parts are missing

### ISSUE THREAD

**Issue by tps800** [Harvey-OS/harvey#1108]
#### Expected behavior
After bootstraping and building ufs shall be installed and usable (if it is part of the build).

#### Actual behavior
After bootstrap and build 
```
export HARVEY=$(pwd)
export PATH=$HARVEY/linux_amd64/bin:$PATH
ufs -root=/$HARVEY -debug=3
```
does not start ninep.
```
#ufs -root=/$HARVEY -debug=3
Der Befehl 'ufs' wurde nicht gefunden, meinten Sie:
  Befehl 'ufw' aus dem Snap ufw (0.36.1)
  Befehl 'fs' aus dem deb openafs-client (1.8.6-1ubuntu1)
  Befehl 'ufw' aus dem deb ufw (0.36-7)
  Befehl 'hfs' aus dem deb hfsutils-tcltk (3.2.6-14)
  Befehl 'zfs' aus dem deb zfsutils-linux (0.8.4-1ubuntu11.2)
  Befehl 'zfs' aus dem deb zfs-fuse (0.7.0-20)
  Befehl 'bfs' aus dem deb bfs (1.7-1)
Informationen zu neuen Versionen sind mit 'snap info <snapname>' zu finden.
```

#### Steps to reproduce
- `./bootstrap.sh`
- `CC=clang ARCH=amd64 build`
- `ufs` is missing in path, ninep does not start.

**Comment by vestein463** [comment]
There is a different subdir ninep under Harvey-OS containing the stuff. 
Though, I think there should be an explanation how to install this.
