### ISSUE TITLE
Experiment with alternate usb stacks

### ISSUE THREAD

**Issue by floren** [Harvey-OS/harvey#1109]
Our current /sys/src/cmd/usb originates from Nix and hasn't been touched in a long time.

Let's pull in USB code from 9legacy and 9front and see if they're a better fit. The kernel code seems pretty uniform, but the userland portions vary, so let's experiment with those.

Ideally, we should be able to copy in the source trees, apply some spatches, and then create build.json files to do the compilation.

https://github.com/Harvey-OS/harvey/pull/1106 has some build.json files that may be a helpful starting point.

QEMU is the most convenient way to do basic testing. For example, you can boot with a USB drive attached by adding `-drive format=raw,file=/tmp/harvey.raw,id=stick,if=none -device usb-storage,drive=stick` to the invocation. Make /tmp/harvey.raw an image with a single partition type 0B, format that partition vfat, and you can boot harvey and run usbfat:

**Comment by gmacd** [comment]
lib differences:
- dev.c
  - legacy: no real differences
  - front: some changes
- devs.c
  - legacy: some changes (small)
  - front: doesn't exist
- dump.c
  - legacy: some changes (small)?
  - front: some changes
- fs.c
  - legacy: some changes (small)?
  - front: doesn't exist
- fsdir.c
  - legacy: no real differences
  - front: doesn't exist
- parse.c
  - legacy: no real differences
  - front: some differences
