### ISSUE TITLE
util/build: rationalize json files

### ISSUE THREAD

**Issue by Shamar** [Harvey-OS/harvey#12]
Since we use json files to guide the build, we should give them a bit more love:

- [ ] replace `..` inclusions with absolute paths (`/` is the `$HARVEY` dir): so we can move folders easily
- [x] inherit CFlags whenever possible
- [x] make architecture-dependent paths depend on $ARCH (see [core.json](https://github.com/Harvey-OS/harvey/blob/master/sys/src/9/amd64pv/core.json#L20-L22)).  
      Requires little changes to [build.go](https://github.com/Harvey-OS/harvey/blob/dd325cbb4286f8a9992f2a992537ea25b5f2dce1/util/src/harvey/cmd/build/build.go)
- [ ] use environment variables in Pre/Post scripts when appropriate (eg [here](https://github.com/Harvey-OS/harvey/blob/master/sys/src/9/amd64pv/core.json#L38) and [here](https://github.com/Harvey-OS/harvey/blob/master/sys/src/9/amd64pv/core.json#L41))

**Comment by sevki** [comment]
on this

**Comment by Shamar** [comment]
@sevki, if you are still working on this, give a look to [this pending CL](https://review.gerrithub.io/#/c/243161/).

I have a small task pending on Cflags (enable extensive debug flags everywhere as I need them for #5), but to avoid Merge Conflict on Gerrit, I can send you a pull request in a branch you prefer.

**Comment by Shamar** [comment]
@sevki in my [debug-everything branch](https://github.com/Harvey-OS/harvey/compare/master...Shamar:debug-everything) you can see the debugging options that I added.

**Comment by sevki** [comment]
@Shamar cool

**Comment by Shamar** [comment]
In b8cfdeab918edba099e71faf034553ba7429de1d @rminnich centralized `Cflags` in [amd64/include/cflags.json](https://github.com/Harvey-OS/harvey/blob/master/amd64/include/cflags.json).

**Comment by elbing** [comment]
A new build tool is in progress.
