### ISSUE TITLE
Using Xen

### ISSUE THREAD

**Issue by zeigerpuppy** [Harvey-OS/harvey#137]
I'd like to try out Harvey-OS as a Xen virtual machine,
is it possible to build as a Xen image?

I am running Xen 4.3 on Debian Wheezy (with ZFSonLinux for my images as zvols).

I'd like to try porting a raytracer to Harvey for use in a rendering cluster.

**Comment by rminnich** [comment]
you should be able to boot harvey as a DomU with no trouble. But who knows.

**Comment by elbing** [comment]
Just try it and tell about us. It sounds interesting.

**Comment by zeigerpuppy** [comment]
great, I'll try giving it a go...

**Comment by elbing** [comment]
Just take an eye to [syslinux/extlinux conf](https://github.com/Harvey-OS/harvey/blob/master/util/SYSLINUX) to see how to boot the kernel.

**Comment by elbing** [comment]
@zeigerpuppy , did you try it finally? any feedback? thanks!

**Comment by zeigerpuppy** [comment]
sorry haven't had a chance yet, chasing a few server bugs at the moment, but should be able to try soon

**Comment by elbing** [comment]
No hurry, We are all interested in seeing if Harvey could run in xen while we keep working in other areas. Thanks!

**Comment by elbing** [comment]
too old, no testers.
