### ISSUE TITLE
Build with -Werror

### ISSUE THREAD

**Issue by rminnich** [Harvey-OS/harvey#14]
We should always be able to build with -Werror

**Comment by elbing** [comment]
Prepare to make casts as a wild tiger. We have tons of warnings.

**Comment by sevki** [comment]
@rminnich my experience with this, as clang is stricter with what is an error breaks the builds. I don't think we can claim this right now. But I think we should close this issue and open issues for targets that aren't being built with -Werror instead of this umbrella it's not working issue.

**Comment by grd** [comment]
The days are getting shorter and the evenings longer... I would like to pick up the warnings again. About Rune, the way I see it there are three possibilities. One is to make Rune int32_t, two is to add (Rune *) in front of each "L" string and the third is something else. Which is preferred?

**Comment by rminnich** [comment]
we changed it to uint on amd64we changed it to uint on amd64

**Comment by grd** [comment]
Yes but isn't that causing all these warnings?

**Comment by rminnich** [comment]
I don't see the point. If we need the change, we need the change, and we deal with the warnings that result. That's what we did on NxM.

**Comment by necktwi** [comment]
on macOS 10.12.2
```
port/getcallerpc.c: In function 'getcallerpc':
port/getcallerpc.c:16:20: error: calling '__builtin_return_address' with a nonzero argument is unsafe [-Werror=frame-address]
  return (uintptr_t)__builtin_return_address(2);
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
port/getcallstack.c: In function 'getcallstack':
port/getcallstack.c:20:21: error: calling '__builtin_return_address' with a nonzero argument is unsafe [-Werror=frame-address]
   pcs[0] = (uintptr)__builtin_return_address(2);
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
port/getcallstack.c:22:21: error: calling '__builtin_return_address' with a nonzero argument is unsafe [-Werror=frame-address]
   pcs[1] = (uintptr)__builtin_return_address(3);
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
port/getcallstack.c:24:21: error: calling '__builtin_return_address' with a nonzero argument is unsafe [-Werror=frame-address]
   pcs[2] = (uintptr)__builtin_return_address(4);
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
port/getcallstack.c:26:21: error: calling '__builtin_return_address' with a nonzero argument is unsafe [-Werror=frame-address]
   pcs[3] = (uintptr)__builtin_return_address(5);
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
port/getcallstack.c:28:21: error: calling '__builtin_return_address' with a nonzero argument is unsafe [-Werror=frame-address]
   pcs[4] = (uintptr)__builtin_return_address(6);
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
port/getcallstack.c:30:21: error: calling '__builtin_return_address' with a nonzero argument is unsafe [-Werror=frame-address]
   pcs[5] = (uintptr)__builtin_return_address(7);
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
2017/01/06 12:16:26 exit status 1

```

**Comment by elbing** [comment]
Mac cross compilers must be referred in flags as another toolchain, like we did with clang or egcc for OpenBSD.

**Comment by necktwi** [comment]
You mean this?
```
$ export TOOLPREFIX=x86_64-elf-
$ ./bootstrap.sh 
$ CC=x86_64-elf-gcc ARCH=amd64 util/build
2017/01/06 13:53:55 exec: "x86_64-elf-x86_64-elf-gcc": executable file not found in $PATH

```

**Comment by elbing** [comment]
Not, /amd64/include/cflags.json
You'll see statements for different paths of toolchains. A PR with one for mac cross-tools is needed there. Or a symlink from x86_64-elf-gcc to gcc, because that's not a canonical name. PR is the right way.

**Comment by necktwi** [comment]
I really don't know what a PR is. But I tried adding either of the following lines to **/amd64/include/cflags.json** and I got the same error.

```
"/usr/local/bin/x86_64-elf-gcc": [
     "-Wno-frame-address"
 ]
```
or
```
"/usr/local/bin/x86_64-elf-gcc": [
     "-mno-implicit-float"
 ]
```

**Comment by elbing** [comment]
Seems I was wrong.
Sadly I haven't a Mac for testing it. Please wait for another team member with MacOS. I'll tell about in slack channels.

**Comment by dancrossnyc** [comment]
I'm down to 171 warnings on my system now. As Ron likes to say, this is close.

**Comment by dancrossnyc** [comment]
All warnings are now gone from userspace. I've similarly excised them from the kernel; I'm tracking down the last few stragglers now but I'm ready to turn on -Werror globally.

**Comment by dancrossnyc** [comment]
...and I've got the last one for RISC-V. So now all architectures are warning free; at least for the default build. And -Werror has been added.

But it also looks like RISC-V is (unrelatedly) broken due to some missing symbols in the keyboard-map driver?

**Comment by rminnich** [comment]
I'll do a pull and take a look.

For temporary, we can take riscv out of the build if you want.

**Comment by dancrossnyc** [comment]
I don't think that's necessary. I've got it linking again, but I don't know
if it actually works.

**Comment by dancrossnyc** [comment]
This is now done.
