### ISSUE TITLE
Get a list of .h files we can remove

### ISSUE THREAD

**Issue by rminnich** [Harvey-OS/harvey#15]
Alvaro has pointed out that there are .h files that we can remove, now that ape is a separate repo. We need the list.

**Comment by elbing** [comment]
I'll use this issue to remove entire ape runtime/dev from main repo.
Software dependent (bzip, awk) but that uses main libs/programs should be
examined individually. There are better versions to work with ansi/posix
environment, but -for historical reasons- perhaps we should keep original
Brian's awk or other software.

Álvaro Jurado Cuevas
www.harvey-os.org
colmenar.biz.tm

**Comment by Shamar** [comment]
I think that, for historical reasons, we should move legendary tools in a Harvey-OS/legends repository.
In the long run, we should port some of them to GCC and Harvey, but it is a low priority task now.

**Comment by elbing** [comment]
I like that dir.

Álvaro Jurado Cuevas
www.harvey-os.org
colmenar.biz.tm
