### ISSUE TITLE
FPU handling is antiquated to the point of uselessness.

### ISSUE THREAD

**Issue by rminnich** [Harvey-OS/harvey#152]
harvey FPU handling derives from plan 9 and it's a joke. It uses the old lazy save model, and that's a reason we can't use the FPU in a note handler, and that's just not going to fly for the long term; we can't ask every use to avoid using printf in a note handler!

We need to look at the recent akaros changes for eager save and use them.

A quick fix is to do an fpu save/restore before and after entering a note handler. But that will take some careful work. Anyone?

**Comment by dancrossnyc** [comment]
I'll take a peek at it.

**Comment by elbing** [comment]
Any clue for where to start?

**Comment by dancrossnyc** [comment]
I'll have a look at what Akaros is doing.

**Comment by rminnich** [comment]
I think that's a good idea. mtaufen really worked hard on that and I think got it right. If we use it, our FP handling will be way more efficient that Plan 9's.

**Comment by elbing** [comment]
It would be in anyway, now it consist in a bunch of asm funcs calling opcodes/instructions...
Where is it in akaros? I would like to give it a go.

**Comment by dancrossnyc** [comment]
Stealing my thunder? :-)

**Comment by gmacd** [comment]
I think it's better now, so closing this.
