### ISSUE TITLE
Refactor libmach

### ISSUE THREAD

**Issue by Shamar** [Harvey-OS/harvey#16]
We should organize libmach so that we can ignore unsupported architectures using `$ARCH`.

Once no `#ifdef` appear in the code, we should remove unsupported architectures (one per CL) referencing this issue, so that we can simply revert the commit when someone will want to restore them.

**Comment by elbing** [comment]
Ok. Let's go.

Álvaro Jurado Cuevas
www.harvey-os.org
colmenar.biz.tm

2015-08-19 23:11 GMT+02:00 Giacomo Tesio <notifications@github.com>:
