### ISSUE TITLE
TOOLPREFIX incorrectly applies to sh

### ISSUE THREAD

**Issue by famousmoose** [Harvey-OS/harvey#166]
#### Expected behavior

When building on OSX, using TOOLPREFIX, we should use the system sh binary.
#### Actual behavior

util/build applied the TOOLPREFIX to sh, and since no x86_64-elf-sh exists the build fails
## On OSX:

export TOOLPREFIX=x86_64-elf- 
./util/build
#### QEMU output

N/A

A workaround is to symlink /bin/sh to x86_64-elf-sh somewhere on your path

**Comment by rminnich** [comment]
thanks for the report. If you can manage with this workaround we can limp along until we get the new build tool, hopefully in june, that's much better.

**Comment by necktwi** [comment]
Its already 2017

**Comment by elbing** [comment]
Yes, but bldy is not ready at all. Sorry for inconvenience.

**Comment by gmacd** [comment]
Isn't this fixed now?

**Comment by rminnich** [comment]
fixed
