### ISSUE TITLE
Fid FID in use error

### ISSUE THREAD

**Issue by rminnich** [Harvey-OS/harvey#17]
When aborting 9p requests we seem to lose track of fids, such that the server thinks they are in use and the kernel does not.

**Comment by rminnich** [comment]
Are we seeing this any more? I suspect this is fixed with the new 9p server. The old one had a serious bug around Tremove.

**Comment by elbing** [comment]
I think this comes from go9p days, not sure if old ninep had this, I had other kind of errors compiling gcc. So for me it's outdated. If new errors rise in actual software, new issues.
