### ISSUE TITLE
After commit eeb309c97cdbbf1aa9921f108bcb7dc2b79efb52 (Bring sdata back into use) Harvey does not boot properly in QEMU

### ISSUE THREAD

**Issue by dmgolubovsky** [Harvey-OS/harvey#189]
Hi,

This is what I have just observed. Going back and forth over the commit log resulted in the isolation of the commit mentioned in the title. I use the following shell script to boot Harvey in QEMU:

https://gist.github.com/dmgolubovsky/2895c66c1b93906c03840cc01fc0aa7a

This script is slightly modified from the original script to run CPU server, just to run a terminal with large resolution (using qxl for video).

Maybe I am doing something wrong, maybe sdata has some unexpected behavior.

#### Expected behavior

Harvey boots with terminal service starting, rio screen appears

#### Actual behavior

The boot process is stuck after starting dns.

#### Steps to reproduce
- git checkout f5bfe81
- ./bootstrap.sh && time ARCH=amd64 util/build
- GO9PRUNT # the script referred to in the first gist

then it boots, starts rio

- git checkout eeb309c
- ./bootstrap.sh && time ARCH=amd64 util/build
- GO9PRUNT # the script referred to in the first gist

then gets stuck on starting dns, and rio screen does not appear.

#### QEMU output

When it boots (before the commit)

https://gist.github.com/dmgolubovsky/c421a9e312a41e88e124046c3c916bfd

When it does not boot (after the commit)

https://gist.github.com/dmgolubovsky/b4fec7eb56db955bc46027cd6af60b15

Thanks.

**Comment by dmgolubovsky** [comment]
But if I change the machine flag to q35,accel=kvm I can boot into rio even with the current master.

QEMU output:

https://gist.github.com/dmgolubovsky/d3656c131f50d9dffb4ddbe9f77837c2

pci(8) output:

https://gist.github.com/dmgolubovsky/b7acdbe4c5bb6f9965387df12c3cc123

What can be the difference making sdata so sensitive?

Thanks.

**Comment by rminnich** [comment]
This is great work, do you mind pasting a diff here of that file, so we have a complete record.

**Comment by dmgolubovsky** [comment]
This is diff between https://gist.github.com/dmgolubovsky/2895c66c1b93906c03840cc01fc0aa7a and the current script. The only meaningful change is replace pc - > q35 in the machine flags. Will be easier to apply manually IMHO.

This is not exactly the GO9PRUN script from the repo, but should work same way in the script from the repo.

--- usr/harvey/tmp/G.pc 2016-06-12 16:35:28.903411636 -0400
+++ /home/golubovsky/bin/GO9PRUNT       2016-06-12 15:12:16.807311129 -0400
@@ -5,6 +5,7 @@
 trap : 2
 
 export HARVEY=$HOME/src/harvey
+export KVM=$HOME/src/kvm-exp/external/qemu-2.6.0/x86_64-softmmu/qemu-system-x86_64
 export KVM=/usr/bin/kvm
 
 $HARVEY/util/ufs -root=$HARVEY &
@@ -13,7 +14,7 @@
 export machineflag=pc
 if [ "$(uname)" = "Linux" ] && [ -e /dev/kvm ]; then
        export kvmflag='-enable-kvm'
-       export machineflag='pc,accel=kvm'
+       export machineflag='q35,accel=kvm'
        if [ ! -w /dev/kvm ]; then
                # we don't have access as a regular user
                export kvmdo=sudo

There is a presentation http://www.linux-kvm.org/images/0/06/2012-forum-Q35.pdf (by someone from the KVM team) explaining differences from the traditional pc (440fx). I am OK just with this workaround so I can continue my work.

Thanks.

**Comment by elbing** [comment]
Well, sdata needs a second round. I440FX needs isa too, I'm preparint devpnp for that. It comes until ICH7 and some nforce/via similar age. Qemu q35 is a ICH9 model which is ahci. Avoiding pc option ensures no error/hang on booting for now. But the problem is that sdata must be fixed at all.

**Comment by elbing** [comment]
Try:

````
kvm -s -m 2048 -monitor stdio -serial /dev/pts/2 -machine q35 -net nic,model=rtl8139 -net user,hostfwd=tcp::1522-:1522 -redir tcp:17010::17010 -redir tcp:17013::17013 -device ahci,id=ahci -drive id=disk,file=$PATH_TO_YOUR/harvey.qcow2,index=0,cache=writeback,if=none -device ide-drive,drive=disk,bus=ahci.0 -append "service=cpu nobootprompt=tcp fs=10.0.2.2 auth=127.0.0.1 nvram=/boot/nvram nvrlen=512 nvroff=0 mouseport=ps2 vgasize=1024x768x8 monitor=vesa" -kernel sys/src/9/amd64/harvey.32bit -vga vmware
````

This will boot with ahci driver.

**Comment by elbing** [comment]
sdata has been dropped. I brought sdata to be compatible with ASUS P5KPL/1600 which is where I have Harvey running in real iron. Sadly, that ICH7 series hasn't AHCI. sdata is old hardware, 32 bit related even if some core duo series were using i440FX model at early 2008. Unless someone has a good sdata driver replacing for legacy IDE/SATA/PATA chipset, Harvey won't support anymore. Source file for now is still in kernel tree, for researching purposes.
