### ISSUE TITLE
Modernize and cleanup libc

### ISSUE THREAD

**Issue by Shamar** [Harvey-OS/harvey#19]
We should:

- [x] remove specialized implementations for platforms we do not maintain
- [x] introduce `const` modifiers where appropriate in function signatures
- [ ] replace `int` arguments with `uint8_t` in memccpy, memchr and [memset](http://stackoverflow.com/a/5919802/412808) (and check if we have any [performance loss](http://stackoverflow.com/a/5919798/412808))
- [ ] fix `gmtime` and `localtime` to get a `Tm *tm` to fill instead of returning static data whose content is overwritten by each call (return value should then be void)
- [x] fix `getcallerpc` signature: the firstarg parameter is not necessary.
- [x] fix `abort` to produce useful messages

**Comment by Shamar** [comment]
I forgot to apply proper [GCC stringification](https://gcc.gnu.org/onlinedocs/cpp/Stringification.html) to [assert(2)](https://github.com/Harvey-OS/harvey/blob/master/sys/include/libc.h#L15).

I'll send a CL tonight.

**Comment by elbing** [comment]
Remaning things aren't essential. Most of the work done.
