### ISSUE TITLE
Move legendary code to Harvey-OS/legends

### ISSUE THREAD

**Issue by Shamar** [Harvey-OS/harvey#20]
Since we need to focus on a working core system we have to postpone the porting and modernization of some valuable tools that we inherited from Plan 9.

To clean up (and to clearly define) our core system, without loosing the connection with our glorious past, we need to move such valuable tools to  [Harvey-OS/legends](https://github.com/Harvey-OS/legends.git), where their portings will be addressed with a lower priority.

Each tool should be moved with related documentation and manual pages in a directory tree resembling its original location.

**Comment by elbing** [comment]
Remains in src/cmd cc and cpp, kenc related.

**Comment by elbing** [comment]
In kernel dir we have some weird things like k10/root or 9/386. Perhaps we need refactor this division. We should talk about in list.

Now that Keith included remaining generated file for normal boot in mksys.go, 9/mk dir is useless. We haven't mk or awk dependencies in kernel.

**Comment by elbing** [comment]
Most of this work is done. Details or little remainings could rise, but that's not justify to leave this open.
