### ISSUE TITLE
ipconfig built with clang fails to complete dhcp process

### ISSUE THREAD

**Issue by rminnich** [Harvey-OS/harvey#203]
#### Expected behavior
Build ipconfig with clang, boot, and clang properly finishes dhcp process.
#### Actual behavior
It hangs -- is it dropping packets, seeing corrupted packets, not handling a lock correctly? it's not clear.

#### Steps to reproduce
- build everything with clang.
- boot and see a hang.
- build sys/src/cmd/ip/ipconfig/ipconfig.json
- CC=clang build sys/src/9/amd64
- hang goes away.

I interpret this as being only an ipconfig issue, and purely from the source in sys/src/cmd/ip/ipconfig, i.e. 3 files. I think we should drop ppp, by the way. I doubt anyone cares about ppp any more -- you can't find serial ports on most hardware, and PPPoE was never a big deal.

**Comment by elbing** [comment]
We always can do a Go program for PPP like any other abandoned old server.

**Comment by sevki** [comment]
@rminnich this is resolved right?

**Comment by rminnich** [comment]
The odd part here is that anything ever worked at all. Ah well.

Fixed.
