### ISSUE TITLE
libc: fix sqrt.s

### ISSUE THREAD

**Issue by Shamar** [Harvey-OS/harvey#21]
The current implementation of [sqrt.s](https://github.com/Harvey-OS/harvey/blob/a7ba5b7b20623d43da90aeb52a3c94dec6d49c21/sys/src/libc/amd64/sqrt.s) segfaults.

Since we have a [C portable version that works](https://github.com/Harvey-OS/harvey/blob/master/sys/src/libc/port/sqrt.c), we temporary remove sqrt.s, to avoid duplicated definitions.

In the long term however, we have to fix sqrt.s since amd64 provides a dedicated instruction.

**Comment by elbing** [comment]
Remove movsd line.

**Comment by elbing** [comment]
Tested:

$ cat sqrt.s 
.globl	mysqrt
mysqrt:
	sqrtsd	%xmm0, %xmm0
	ret

$ cat sqrtmain.c 
#include <u.h>
#include <libc.h>

double mysqrt(double x);

int main ()
{

   print("Square root of %lf is %lf\n", 4.0, mysqrt(4.0) );
   print("Square root of %lf is %lf\n", 5.0, mysqrt(5.0) );
   
   return(0);
}

Compile, link for Harvey and see.

**Comment by Shamar** [comment]
Very cute: a line removed is a line debugged! :+1:

**Comment by elbing** [comment]
I think stack dancing after deeply Aki's change this summer must be changed. There's no need to copy arg in xmms from 16(%rdi), that will be done by instruction.

I saw perhaps would be better to add and fsqrt assembly source, but I don't know what's the state of floating point co-processor in Harvey. Plan9 hadn't SSE3 or 4v2 and maybe there are more things forgotten that need to be added in lib and kernel.

Rest of assembly in libc must be tested.
My test example could be used for regress, please look at the rest and implement it. Then all in one CL (dropping sqrt.c, adding sqrt.s and regression test).

Thanks Giacomo!
