### ISSUE TITLE
pci(8) prints memory addresses as negative hexadecimal numbers

### ISSUE THREAD

**Issue by dmgolubovsky** [Harvey-OS/harvey#231]
After the format conversion (not using u as unsigned flag) output of pci(8) where %.8lx is used to format the BAR base address changed so memory addresses print as negative:

#### Expected behavior (this is from saved pci output a while ago, so addresses are different, but you get the idea)
0.4.0:  virtio-9p      00.02.00 1af4/1009  10 0:0000c101 64 *1:fc094000* 4096
0.5.0:  virtio-console 07.80.00 1af4/1003  10 0:0000c281 32 1:fc095000 4096
0.6.0:  virtio-scsi    01.00.00 1af4/1004  11 0:0000c141 64 1:fc096000 4096
0.7.0:  virtio-disk    01.00.00 1af4/1001  11 0:0000c181 64 1:fc097000 4096

#### Actual behavior
0.6.0:  virtio-console 07.80.00 1af4/1003  11 0:0000c2c1 32 *1:-03f6a000* 4096
0.7.0:  virtio-scsi    01.00.00 1af4/1004  11 0:0000c181 64 1:-03f69000 4096
0.8.0:  virtio-disk    01.00.00 1af4/1001  10 0:0000c1c1 64 1:-03f68000 4096
0.9.0:  virtio-rng     00.ff.00 1af4/1005  10 0:0000c2e1 32

#### Steps to reproduce

run the pci script 

Using lX instead of lx does not have any effect.

**Comment by elbing** [comment]
x is unsigned, very weird effect. Sorry for the stupid question, but, Are you sure you rebuilt all, including libs and cmd?
I looked at 9/386/pci.c and 9/port/devpci.c and prints funcs look ok. Also x and X worked for me during aux/vga debugging last week.

Actual build tool is some tricky, so it would be better if you ensure you removed all under /amd64/lib and /amd64/bin for having only new libs and programs. Or just a `git clean -f -n` if you haven't any untracked you want to keep.

**Comment by dmgolubovsky** [comment]
I'll check if I did complete rebuild.
Thanks.

**Comment by dmgolubovsky** [comment]
If %.8llx is used instead of %.8lx then all addresses are printed OK. I'll do a pull request for this. Not sure if there is any bug in dofmt.c, my own reading does not show any wrong logic, but maybe this finding helps find it.
