### ISSUE TITLE
Sporadic mouse movements in kvm on commit 8ef0e4f, other interrupt-related problems

### ISSUE THREAD

**Issue by dmgolubovsky** [Harvey-OS/harvey#272]
#### Expected behavior

Normal mouse cursor movement (following the physical mouse movements)

#### Actual behavior

Sporadic mouse cursor movements

#### Steps to reproduce
- git checkout 8ef0e4f
- cd $HOME/src/harvey
- ./bootstrap.sh && ARCH=amd64 util/build

#### QEMU output
[bootlog.8ef0e4f.txt](https://github.com/Harvey-OS/harvey/files/440488/bootlog.8ef0e4f.txt)

Note the line 

5ffff00: mutiple irq bus 255 dev 48, it does not seem to be there before.

I keep developing the virtio drivers, so there is some code not yet committed into the main Harvey repo, this code is only available from my repo, see https://github.com/dmgolubovsky/harvey/tree/v9p

I rebased my changes on the top of the main repo (commit 8ef0e4f). When I boot Harvey I get this:

[bootlog.v9p.txt](https://github.com/Harvey-OS/harvey/files/440490/bootlog.v9p.txt)

Note lines like these (repeats for every virtio device):

acpi_make_rdt(0xc002000 11 0 0x10)
mutiple irq botch bus 0 0/11/16 lo 32768 vs 32857
Unable to build IOAPIC route for irq 11
intrenable: couldn't enable irq 11, tbdf 0xc002000 for virtio-net-0

This happens when I call intrenable for every virtio device identified. At some point before I was able to see all interrupts assigned in /dev/irqalloc, now I only see the first virtio device with assigned interrupt.

Other side note (not sure related or not, maybe deserves its own bug report). I used an Intel-based host:

[cpuinfo.intel.txt](https://github.com/Harvey-OS/harvey/files/440494/cpuinfo.intel.txt)

and now moved my development to an AMD-based host:

[cpuinfo.amd.txt](https://github.com/Harvey-OS/harvey/files/440495/cpuinfo.amd.txt)

Worth noting that kvm option -cpu host does not work on AMD-based computers at all (Harvey dies right at the start of boot, the same happens with -cpu athlon or any other AMD CPU). Setting -cpu pentium or -cpu kvm64 makes Harvey boot, and at the commit the behavior is same on both computers. I tried to bisect the recent commits to find when the interrupts were broken, and noticed that on many previous commits AMD-based host could not boot Harvey even with -cpu pentium (it died with message mount:unknown user 22) while on the Intel-based host it booted although the mouse movement problem was there. Bisecting did not give me anything though (I did it on AMD, maybe I need to repeat it on Intel).

I'll keep researching this, in case I have more findings I'll post them.

Thanks.

**Comment by elbing** [comment]
I saw mouse problem this week. I commented it to Ron, thinking it was acpi related. I use kvm over an Intel.
Abou AMD cpu detection, I have it in real machine with and Athlon x4 right detected. In Qemu Opterons must be the right smp number of processor or it could fail. With kvm I just don't specify, because paravirtualization is thought to allow vm see the real cpu.
-cpu pentium won't work because it's 32 bits.

I'll invest this. Multiple irq message is shown since new acpi is in.

**Comment by elbing** [comment]
Oh in real hardware (Asus A1M1) irq 10 and 11 are failing to me too. In that machine are usb related.

**Comment by elbing** [comment]
Finally, tell me what real AMD are you using for kvm -cpu host to fail. Perhaps its id must be added to func which rdmsr some info about in what cpu it's booting. This happened in past.

**Comment by dmgolubovsky** [comment]
I included a link to cpuinfo (https://github.com/Harvey-OS/harvey/files/440495/cpuinfo.amd.txt) - this is about the real AMD. The computer is HP 6005 SFF produced I think in 2010 (so not a new model) which I once bought on Overstock cheap, added storage and memory, now it is an usable computer despite its age.

Thanks.

**Comment by rminnich** [comment]
The botch is because two IRQs got the same interrupt slot but one is edge and one is level.

This is a problem. The USB problem elbing is seeing is not the same problem. If you can start pushing virtio PRs we can start to look at it.

**Comment by dmgolubovsky** [comment]
I can push what I have, however it is only the kernel part, no userland (I still need to add few code to actually access the virtqueue via read-write, but this is not a lot). This does not interfere with anybody else's projects, so safe to add even if it does not work. I held it separate because the code was not really ready for review, now it is more ready though not perfected/polished.

OTOH as I am targeting a virtualized environment, the question is if it is possible to "neutralize" ACPI (via kernel command line, or alternative build json file to supply a dummy replacement to make the linker satisfied). For a guest-only kernel the hardware model can be greatly simplified. I might assume in the future a lightweight tool like "native KVM" which should provide only minimum "hardware" to talk to the host.

I tried "-no-acpi" in KVM parameters, the kernel did not boot (but I did not research this deeply).

Thanks.

**Comment by rminnich** [comment]
neutralizing acpi is not really practical, we're stuck with it. Every firmware for qemu/kvm as acpi tables. We just need to accept it.

**Comment by rminnich** [comment]
Plus, your problem with the multiple irq botch would occur with the old system too. It's not really an acpi problem. You might want to dig into where that message is generated just so you can see what it is.

**Comment by rminnich** [comment]
32768 is x08000
32857 is 0x8059
SO look at the source.
See where that mesage is printed and what it might mean.

**Comment by dmgolubovsky** [comment]
At some point (around Aug 12) I did not have either problem: intrenable worked for all virtio devices, and mouse worked well (I tested my own code how interrupts were assigned, so would notice). This was the time when ACPICA code was removed and then added. Not trying to argue, just an observation. I took a break from Harvey development after Aug 12, just resumed yesterday.

I'll look into the sources. Would it make sense to print these addresses in hex?

Thanks.

**Comment by rminnich** [comment]
they are not addresses but yes it would make sense to print them in hex. I don't know why I printed them in decimal.

[3:48]  
Thanks for looking into this. Sorry for the mess.

[3:49]  
I wonder why the virtio devices are on bus 2 however? Is there a virtio bridge device in there somewhere? Can you append a pci command to this so we can see it?

**Comment by rminnich** [comment]
I see what's going on. Any chance you could convince the virtio devices to use interrupts 12 and 13?

**Comment by rminnich** [comment]
They are colliding with 2/0 (whatever that is) and the 8139. Those devices seem to want different interrupt types than virtio. 

If you can get virtio on different IRQs (interrupt lines 12 and/or 13) that might do the trick.
key text:

0   2/0 03 00 00 1b36 0100 B  10  0:f4000000 67108864 1:f8000000 67108864 2:fc090000 8192 3:0000c201 32 
0   3/0 02 00 00 10ec 8139 B  11  0:0000c001 256 1:fc092000 256 

these two "physical" devices have different requirements than these virtio devices.
0   4/0 02 00 00 1af4 1000 B  11  0:0000c221 32 1:fc093000 4096 
0   5/0 00 02 00 1af4 1009 B  10  0:0000c101 64 1:fc094000 4096 
0   6/0 00 02 00 1af4 1009 B  10  0:0000c141 64 1:fc095000 4096 
0   7/0 07 80 00 1af4 1003 B  11  0:0000c241 32 1:fc096000 4096 
0   8/0 01 00 00 1af4 1004 B  11  0:0000c181 64 1:fc097000 4096 
0   9/0 01 00 00 1af4 1001 B  10  0:0000c1c1 64 1:fc098000 4096 
0  10/0 00 ff 00 1af4 1005 B  10  0:0000c261 32 
0  11/0 00 ff 00 1af4 1002 B  11  0:0000c281 32

**Comment by rminnich** [comment]
option two: since you're doing virto, don't set up the 8139 and see if things get a tiny bit better.

**Comment by rminnich** [comment]
/usr/bin/kvm -s -cpu kvm64 -smp 1 -m 2048 -enable-kvm -serial stdio --machine pc -net user,hostfwd=tcp::5555-:1522 -net dump,file=/tmp/vm0.pcap -vga qxl -display sdl -no-frame -append "service=terminal nobootprompt=tcp fs=10.0.2.2 auth=127.0.0.1 nvram=/boot/nvram nvrlen=512 nvroff=0 user=harvey mouseport=ps2 vgasize=1920x1080x24 monitor=vesa" -fsdev local,path=//home/golubovsky/src/harvey/usr/harvey/tmp,id=harvtmp,security_model=none -device virtio-9p-pci,fsdev=harvtmp,mount_tag=harvtmp -fsdev local,path=/tmp,id=fstmp,security_model=none -device virtio-9p-pci,fsdev=fstmp,mount_tag=hosttmp -device virtio-serial-pci -device virtio-scsi-pci -drive file=/home/golubovsky/Downloads/Fedora-Workstation-netinst-x86_64-24-1.2.iso,id=xyz,if=none -device virtio-blk-pci,drive=xyz -device virtio-rng-pci -net nic,model=virtio -balloon virtio -redir tcp:9999::9 -redir tcp:17010::17010 -redir tcp:5356::5356 -redir tcp:17013::17013 -kernel /home/golubovsky/src/harvey/sys/src/9/amd64/harvey.32bit

notice I removed the 8139.

**Comment by dmgolubovsky** [comment]
Removal of 8139 does not help at the moment because I don't have the virtio-net driver. Here are my further observations:

- Removed all virtio devices. Mouse still does not work well, but botched IRQs disappeared (expectable)
- In pci.c forced interrupt line 10->12 and 11->13* for all virtio devices (by writing into the proper PCI register, and then reading from there and comparing). Now it says in the boot log:

acpi_make_rdt(0xc005800 13 0 0x2c)
Non-ISA IRQ 13 not found in MADT, aborting
Unable to build IOAPIC route for irq 13
intrenable: couldn't enable irq 13, tbdf 0xc005800 for virtio-balloon-7

And the dump of MADT (/dev/ACPI/pretty):

acpi: MADT@fffffffff071d230: lapic paddr fee00000 pcat 1:
        lapic pid 0 id 0
        ioapic id 0 addr fec00000 ibase 0
        intovr irq 0 intr 2 flags $0[polarity/trigger like in ISA,BOGUS TRIGGER]
        intovr irq 5 intr 5 flags $d[active high,level]
        intovr irq 9 intr 9 flags $d[active high,level]
        intovr irq 10 intr 10 flags $d[active high,level]
        intovr irq 11 intr 11 flags $d[active high,level]
        lnmi pid 255 lint 1 flags $0

means that the current configuration does not know IRQ 12 and 13.

I checked my older boot logs. The layout of IRQs and pins was the same. At the time when pcirouting() function was in pci.c this did not cause problems with intrenable (thought I did not test actual interrupts from virtio).

I ran lspci -vv  on Fedora 24 running in KVM. Virtio devices use interrupt 10 and 11. How does Linux get away with this?

Thanks.

-----------------------------------------
* I don't feel that such deliberate forcing of IRQ's is acceptable beyond experientation. Is there any way to tell at the time of PCI initialization which interrupts are available (perhaps by scanning MADT - is it available at this moment)?

**Comment by rminnich** [comment]
I'd still appreciate it if you could do a test of removing the 8139 as I expect it will remove the conflict on irq 11.

I would also be useful to find out what the meaning of the conflict is. It may be something that's easy to deal with. I'm not near the code right now or I would look -- sorry!

**Comment by rminnich** [comment]
Thanks for trying 12 and 13, sorry it did not work. I did not realized the MADT was so unpopulated.

OK, the conflict (botch) is that virtio and hardware are using the same RDT entry in the ioapic but the lo (see code) value for 8139 is not the same as for the virtio. The setup code is just saying that it does not know what to do. We need to look at the computation of lo and see why. Resolution of this problem may be simple.

Let's get your code up to master so more of us can take a look. It's really great to have you looking at this.

**Comment by dmgolubovsky** [comment]
I tried removing 8139, the PCI table (virtio interrupts are remapped) looks like:

bus dev type vid  did intl memory
0   0/0 06 00 00 8086 1237 A   0  
0   1/0 06 01 00 8086 7000 A   0  
0   1/1 01 01 80 8086 7010 A   0  4:0000c1a1 16 
0   1/3 06 80 00 8086 7113 B   9  
0   2/0 03 00 00 1b36 0100 B  10  0:f4000000 67108864 1:f8000000 67108864 2:fc050000 8192 3:0000c101 32 
0   3/0 02 00 00 1af4 1000 B  13  0:0000c121 32 1:fc052000 4096 
0   4/0 00 02 00 1af4 1009 B  13  0:0000c001 64 1:fc053000 4096 
0   5/0 00 02 00 1af4 1009 B  12  0:0000c041 64 1:fc054000 4096 
0   6/0 07 80 00 1af4 1003 B  12  0:0000c141 32 1:fc055000 4096 
0   7/0 01 00 00 1af4 1004 B  13  0:0000c081 64 1:fc056000 4096 
0   8/0 01 00 00 1af4 1001 B  13  0:0000c0c1 64 1:fc057000 4096 
0   9/0 00 ff 00 1af4 1005 B  12  0:0000c161 32 
0  10/0 00 ff 00 1af4 1002 B  12  0:0000c181 32 

that is nobody is claiming 11 so there will be no conflict. But it does not go much further because no network, so no root can be mounted on the host. I'll try with unmapped virtio IRQ later.

I'll send  a PR tonight with my code (should I keep virtio interrupts at 12 and 13, or put them back to 1/11?)

Thanks.

**Comment by elbing** [comment]
Please, test #273 in your real AMD machine. Thanks!

**Comment by dmgolubovsky** [comment]
mouseenable() is called twice which causes the "multiple irq" message. I commented out the call to mouseenable() in main.c now only one remains in mouse.c Subjectively mouse movements became less sporadic although it disobeys sometimes. No conclusions yet, just an observation.

**Comment by rminnich** [comment]
that's interesting but ... the way mouseenable gets called twice seems like it can happen with ps2mouse. 

So, question, why do we still do aux/mouse ps2? Because the mice are all usb at this point I thought. What's the reason to try to set up a ps2 mouse?

I'm all for removing all ps2mouse references. The mouseenable in main.c is the proper one to call I think.

**Comment by dmgolubovsky** [comment]
Is USB mouse currently supported in Harvey? I can specify in KVM to provide an USB pointer device.

**Comment by dmgolubovsky** [comment]
I printed the trace of the messages that ms.c writes to /dev/mousein. I see sometimes the X or Y coordinates are way too large (maybe related to %x format conversion):

m 0x1 0x0 0x0
m 0x3 0x0 0x0
m 0x1 0x0 0x0
m 0x1 0x0 0x0
m 0x3 0xfffffffe 0x0
m 0x1 0xffffffff 0x0
m 0x1 0x0 0x0
m 0x1 0xffffffff 0x0
m 0x1 0x0 0x0
m 0x1 0xffffffff 0x0
m 0x1 0x0 0x0
m 0x1 0x0 0x0
m 0x2 0x0 0x0
m 0x1 0x0 0x0
m 0x2 0xfffffffe 0x0
m 0x2 0x0 0x0
m 0x1 0x0 0x0
...
m 0x0 0x1 0x0
m 0x0 0x3 0x0
m 0xffffffff 0x3 0x0
m 0x0 0x2 0x0
m 0xfffffffe 0x4 0x0
m 0x0 0x2 0x0
m 0xfffffffe 0x4 0x0
m 0xffffffff 0x2 0x0
m 0xffffffff 0x4 0x0
m 0xffffffff 0x2 0x0
m 0xfffffffd 0x6 0x0
m 0xffffffff 0x3 0x0
m 0xffffffff 0x3 0x0

Is it possible that these supposedly negative numbers are treated as large positives? Will look further into this.

**Comment by dmgolubovsky** [comment]
This fix:
```c
diff --git a/sys/src/cmd/ms.c b/sys/src/cmd/ms.c
index 4916878..9a3e60b 100644
--- a/sys/src/cmd/ms.c
+++ b/sys/src/cmd/ms.c
@@ -94,7 +94,7 @@ main(int argc, char *argv[])
                        dx = msg[1];
                        dy = -msg[2];
                        //mousetrack(dx, dy, buttons, TK2MS(MACHP(0)->ticks));
-                       fprint(mousefd,"m %#x %#x %#x\n", dx, dy, buttons);
+                       fprint(mousefd,"m %d %d %#x\n", dx, dy, buttons);
                }
        }
 }
```
seems to fix the sporadic movement. Basically, mouse movement is passed in decimal rather than in hex so negatives are decoded as needed. Not sure why this broke: the ms.c code was not changed recently nor was strtol.c

Whoever noticed sporadic mouse movements please test this diff.

Ron: can you try this with your ps2 mouse removal PR or is it better that I push this change?

Thanks.

**Comment by rminnich** [comment]
NICE CATCH! Let's try it.

I think we need both things? 

LGTM

**Comment by rminnich** [comment]
USB mouse will work only if USB works, and the state of ACPI is such that it's not working on platforms with USB on the other side of PCI-PCI bridges, sorry. It's close.

**Comment by dmgolubovsky** [comment]
Ron, would you like to apply this patch (ms.c) to your current PR? It will solve both multiple IRQ and mouse movements. If not, I'll make this a separate PR.

Thanks.

PS In the world of touchscreens we may need a way to report absolute pointer position (perhaps devmouse should expose the "mouseabs" file entry where in a similar way pointer *position* and button mask are written by an userland program).

**Comment by rminnich** [comment]
let's keep them two PRs, it just makes things more clear. Thanks for catching this bug. 
mouseabs sounds fine to me.

**Comment by dmgolubovsky** [comment]
OK, will do a PR tonight. Mouseabs is for the future ;)

Thanks.

**Comment by elbing** [comment]
I'll test mouse tonight, if all goes well, this issue will be gone.

**Comment by elbing** [comment]
Fixed. Thanks @dmgolubovsky .
