### ISSUE TITLE
Remove Dist

### ISSUE THREAD

**Issue by sevki** [Harvey-OS/harvey#276]
#### Expected behavior
dist and replica should not exist
#### Actual behavior
they exist.

**Comment by rminnich** [comment]
ah, sorry, fixed. but I forget to indicate that in the PR. How do you do that again?

**Comment by sevki** [comment]
something like `closes #276` 

complete list of verbs you can use to close issues via commit messages
- close
- closes
- closed
- fix
- fixes
- fixed
- resolve
- resolves
- resolved
