### ISSUE TITLE
boot: remove /util/nvram from RamFiles

### ISSUE THREAD

**Issue by Shamar** [Harvey-OS/harvey#28]
build.json includes /util/nvram to ease integration of factotum during development.

However, we don't want every Harvey node in the world to have the same hostowner and password.

**This is a reminder** until Harvey could be distributed with an install program which sets up nvram.

**Comment by elbing** [comment]
Not, sure. But we want that people who knows nothing about can boot a cpu
server by default until they can learn how to make their own nvram. That
was the purpose. As with go9prun script.

Álvaro

**Comment by Shamar** [comment]
Yes, this is fine for development (just like GO9PRUN), but this issue is a memento for the future.
We don't want our first stable release to be installed this way from CD.

**Comment by elbing** [comment]
I understanded it when I read gerrit. Ok, I'm sorry.

Álvaro

**Comment by sevki** [comment]
@elbing has this been resolved?' there are some commits related to this?
