### ISSUE TITLE
Clean up the ACPI code

### ISSUE THREAD

**Issue by rminnich** [Harvey-OS/harvey#288]
The ACPI kernel, user, and library code works. It's not pretty. If someone wants a beginner project they can look into cleaning up the kernel code and libacpi.

**Comment by andy5995** [comment]
Has the status of this ticket changed? What files need to be looked at?

**Comment by rminnich** [comment]
sys/src/cmd/acpi/irq.c to start, but also sys/src/cmd/libacpi/*.c

**Comment by rminnich** [comment]
easy free advice: your commits should be small and very focused; keep them to 25 lines or less.

**Comment by elbing** [comment]
**Before** jumping in this pool, please **read our [minimal style guide](https://github.com/Harvey-OS/harvey/wiki/Style-Guide)** and then ask about doubts in [Slack](https://harvey-slack.herokuapp.com/) or in [Mailing List](http://groups.google.com/forum/#!forum/harvey).
Thanks and welcome!

**Comment by elbing** [comment]
Status is "it works" and Dan Cross cleaned warnings properly as with rest of the sources. It would better that @rminnich (author) could give you a few clues about.

**Comment by gmacd** [comment]
Spring cleaning - closing old issues
