### ISSUE TITLE
kernel: stabilize the system api

### ISSUE THREAD

**Issue by Shamar** [Harvey-OS/harvey#29]
We need a minimal set of simple and powerful syscalls that can be considered stable.

Thus we have to replace syscalls that can be expressed in term of the others (eg `sleep` and `alarm` can be moved to user space using `awake`) and decide what to do with those syscalls that we inherited but are not currently available in any C header (maybe some are going to be removed and others to be improved).

**Comment by elbing** [comment]
_errstr was still used in APE. Fixed.
The Kernel API won't be touched for a while.
