### ISSUE TITLE
error strings are broken

### ISSUE THREAD

**Issue by rminnich** [Harvey-OS/harvey#294]
#### Steps to reproduce
/bin/ls bee hive hurts nose so do not climb tree

#### Actual behavior
/bin/ls -l bee hive hurts nose so do not climb tree
ls: bee: 'bee' file does not exist
ls: hive: 'hive'
ls: hurts: 'hurts' 'bee' file does not exist
ls: nose: 'nose' 'hive'
ls: so: 'so' 'hurts' 'bee' file does not exist
ls: do: 'do' 'nose' 'hive'
ls: not: 'not' 'so' 'hurts' 'bee' file does not exist
ls: climb: 'climb' 'do' 'nose' 'hive'
ls: tree: 'tree' 'not' 'so' 'hurts' 'bee' file does not exist

#### Expected behavior
the file names, one per line, with the error 'not found'
ls: bee: No such file or directory
ls: climb: No such file or directory
ls: do: No such file or directory
ls: hive: No such file or directory
ls: hurts: No such file or directory
ls: nose: No such file or directory
ls: not: No such file or directory
ls: tree: No such file or directory

**Comment by andy5995** [comment]
I don't understand [L10](https://github.com/Harvey-OS/harvey/blob/25448610cc42d2f741b8042bde1cc6a68bf275e4/sys/src/cmd/ls.c#L110).

Why are there two format specifiers but only one arg in the list?

What does %r specify?

I'm not an expert, but wanted to take a look anyway. ;)

I'm using Debian Linux. Is there a method I can use to only build ls.c? I used this command but of course it failed:
`gcc -Wall -I/home/andy/src/harvey/amd64/include -I /home/andy/src/harvey/sys/include ls.c -o ls`

**Comment by elbing** [comment]
Yes, you missed LDFLAGS, but due to default options that gcc passes to ld, you can't link it directly:

```gcc -std=c11 -I /home/andy/src/harvey/amd64/include -I /home/andy/src/harvey/sys/include -I . -Wno-frame-address -ffreestanding -fno-builtin -fno-omit-frame-pointer -g -gdwarf-2 -ggdb -mcmodel=small -mno-red-zone -O0 -static -Wall -Wno-missing-braces -Wno-parentheses -Wno-unknown-pragmas -c ls ls.c; ; ld -o ls ls.o -L /home/andy/src/harvey/amd64/lib -static -e_main -lbio -lc```

Take an eye in `/amd64/include/cflags.json` and `/sys/src/cmd/cmd.json`

**Comment by hdonnay** [comment]
`%r` is the errstr verb.
The relevant man pages are [errstr(2)](http://man.cat-v.org/plan_9/2/errstr) and [print(2)](http://man.cat-v.org/plan_9/2/print). It's another one of those Plan 9 things that seems odd, but is mad useful.

**Comment by elbing** [comment]
And that's the issue treated here :-).

**Comment by rminnich** [comment]
Fixed by https://github.com/Harvey-OS/ninep/pull/15

**Comment by andy5995** [comment]
Thank you for the reply. I see this is fixed, so I'll forget about trying to build 'ls.c'.

I tried to build a full harvey though. It built, but I had a problem getting it to run with qemu. I'll find the appropriate place to start that discussion though.

**Comment by elbing** [comment]
We have available our mailing list and slack channels. Go to harvey-os.org and see there in community section for choosing you would like more :-).

**Comment by andy5995** [comment]
I joined your slack channel, went through the build process like I did last time, ran the command mentioned on your Getting Started page. It booted this time. Thanks. :)
