### ISSUE TITLE
Bring back awk; then fix venti/conf and fossil/conf

### ISSUE THREAD

**Issue by rminnich** [Harvey-OS/harvey#30]
These two scripts need awk and we've worked around it by commenting awk out.

Let's get an awk we can use.

**Comment by elbing** [comment]
Ape is gone, but working. You can use its runtime/headers to compile plan9
awk.

First try to glib? I was seeing akaros port and looks easy to begin. Satan
will come later.

Álvaro

**Comment by elbing** [comment]
Field is here thanks to Dan, doing a little job what we needed from awk. I think this issue can be closed for now, because we have got rid off awk issue. Works on awk and rest of ansi world will come in future.
