### ISSUE TITLE
drawterm: login errors are broken

### ISSUE THREAD

**Issue by hdonnay** [Harvey-OS/harvey#300]
#### Expected behavior

Drawterm should report a useful error string.
#### Actual behavior

Garbage gets written to the screen.
#### Steps to reproduce
- drawterm into harvey: `drawterm -c localhost -u harvey`
- enter a random string
- drawterm says something like:

```
cpu: server says: cpu: srvauth: auth_proxy rpc write: <garbage> auth protocol botch
```

Sometimes it doesn't even get that last part out.

This probably means we messed up the auth protocol somewhere?

**Comment by elbing** [comment]
Hank, after ufs improvements, does this happening yet?

**Comment by elbing** [comment]
`/lib/ndb/local` it's not properly set, since Harvey is not being installed yet. So This will be gone when a complete cpu server set up would be done over a disk and not using the git tree.
