### ISSUE TITLE
port code from 386/ directory to port/ or architectures

### ISSUE THREAD

**Issue by rminnich** [Harvey-OS/harvey#352]
code in 386/ is limited to 32-bit addresses (as in ahci before we fixed it) or references things we no longer use, like the ISA bus. 

We need to eliminate this directory, but we have to do it carefully; each driver has to be checked for 32 bit limitations or other problems. This is not a simple git mv issue.

**Comment by gmacd** [comment]
Spring cleaning - closing old issues
