### ISSUE TITLE
Qemu issues

### ISSUE THREAD

**Issue by elbing** [Harvey-OS/harvey#38]
This issue is open to note here all the things we are finding about problems running Harvey in Qemu, hacks made for this or broken things.

Delay in boot:
https://review.gerrithub.io/#/c/259279/

main.c:178
"// FIX QEMU. extern int64_t hz;
	int64_t hz;"

**Comment by elbing** [comment]
Possible bug in authdial. Noted in [Harvey group list](http://groups.google.com/forum/#!forum/harvey).

**Comment by rminnich** [comment]
This is old and points to gerrithub. Further, I think the boot time issues are fixed by my clang-inspired fix to the ioapic and setting up port forwarding. We can reopen this if there's other issues I did not know about.
