### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Fluray** [Harvey-OS/harvey#39]
2016/02/19 16:20:34 /usr/bin/ld -o nfs nfs.o -static -e_main -lavl -lcomplete -lcontrol -ldisk -lflate -lframe -lgeometry -lhttpd -lbin -llex -lmemdraw -lmemlayer -lmemdraw -ldraw -lplumb -lregexp -lstdio -lString -lsunrpc -loventi -l9p -lauth -lauthsrv -lndb -lip -lventi -lsec -lauth -lmp -lthread -lmach -lbio -lc -L /home/ubuntu64/harvey/amd64/lib
nfs.o：在函数‘mountMnt’中：
/home/ubuntu64/harvey/sys/src/cmd/nfs.c:130：对‘nfs3Errstr’未定义的引用
nfs.o：在函数‘nfsGetattr’中：
/home/ubuntu64/harvey/sys/src/cmd/nfs.c:191：对‘nfs3Errstr’未定义的引用
nfs.o：在函数‘nfsAccess’中：
/home/ubuntu64/harvey/sys/src/cmd/nfs.c:217：对‘nfs3Errstr’未定义的引用
nfs.o：在函数‘nfsMkdir’中：
/home/ubuntu64/harvey/sys/src/cmd/nfs.c:252：对‘nfs3Errstr’未定义的引用
nfs.o：在函数‘nfsCreate’中：
/home/ubutu64/harvey/sys/src/cmd/nfs.c:291：对‘nfs3Errstr’未定义的引用
nfs.o:/home/ubuntu64/harvey/sys/src/cmd/nfs.c:327: more undefined references to `nfs3Errstr' follow
nfs.o：在函数‘nfsReadDirPlus’中：
/home/ubuntu64/harvey/sys/src/cmd/nfs.c:544：对‘nfs3EntryPlusUnpack’未定义的引用
nfs.o：在函数‘nfsReadDir’中：
/home/ubuntu64/harvey/sys/src/cmd/nfs.c:590：对‘nfs3Errstr’未定义的引用
/home/ubuntu64/harvey/sys/src/cmd/nfs.c:597：对‘nfs3EntryUnpack’未定义的引用
nfs.o：在函数‘threadmain’中：
/home/ubuntu64/harvey/sys/src/cmd/nfs.c:1576：对‘nfs3Prog’未定义的引用
nfs.o：在函数‘dialproc’中：
/home/ubuntu64/harvey/sys/src/cmd/nfs.c:1643：对‘nfs3Prog’未定义的引用
2016/02/19 16:20:34 exit status 1

**Comment by elbing** [comment]
Removed cmd/nfs.c offending program. Old.Nfs3 is gone.
