### ISSUE TITLE
Booting CPU on real hardware doesn't enable USB keyboard

### ISSUE THREAD

**Issue by gmacd** [Harvey-OS/harvey#452]
#### Expected behavior
Once the command prompt is shown, I should be able to type using a USB or PS/2 keyboard.

#### Actual behavior
Keypresses from the USB keyboard aren't detected. If I plug in the same keyboard via a PS/2 adaptor, it works.

#### Steps to reproduce
Boot cpu on real hardware (in this case an AT5IONT-I), with USB keyboard attached.  Wait for prompt.  Press keys.  See nothing happen.

**Comment by rminnich** [comment]
Did usb processes start up?

**Comment by gmacd** [comment]
It seemed to.  I'll see if I can attach a photo of the output...

**Comment by gmacd** [comment]
![usb](https://cloud.githubusercontent.com/assets/698187/23437276/6699a7f8-fe05-11e6-8ead-4acdb238c572.JPG)

**Comment by rminnich** [comment]
newhub failed is a bad sign.

**Comment by gmacd** [comment]
![image](https://user-images.githubusercontent.com/698187/40206507-4139712a-5a28-11e8-81d0-444d30e30fce.png)

Bug still exists, at least on my machine with my keyboard.

**Comment by gmacd** [comment]
As stated in slack:

I'm trying to get qemu to provide a usb keyboard atm.  Apparently it defaults to ps2.

If I run `./util/GO9PTERM -device usb-kbd` I see logging of `usb/kbd...`, which I wouldn't normally see.  Once I open a term window the keyboard generated junk.

If I run `./util/GO9PCPU -device usb-kbd -usb` I see the same thing I see on my own hardware - no sign of any keyboard activity.

One last thing is if I pass `-device usb-mouse`, then the mouse no longer works (with GO9PTERM), but that's not very surprising now.
