### ISSUE TITLE
USB keyboard via PS/2 initialised incorrectly when inserted before boot (cpu)

### ISSUE THREAD

**Issue by gmacd** [Harvey-OS/harvey#454]
#### Expected behavior
I have a USB keyboard, connected via a PS/2 adaptor.  It has with no keypad.  The keypad buttons overlap with the right hand side of the letters (e.g. 456 = UIO).  These keys can be used if the 'fn' toggle button is toggled on.  This behaviour should be off by default.

#### Actual behavior
If I remote boot cpu on real hardware with this keyboard connected via PS/2, the numeric keypad is enabled.  The toggle key doesn't toggle - I need to hold it down to use the default letter keys.

However, if I unplug and plug the keyboard in again, it behaves better, with the letters on by default, the numeric keys working if the fn button is pressed.

Given the keyboard is really a USB keyboard, I'm not sure the toggle button behaviour (press once to turn on, again to turn off) can be achieved (it doesn't work this way in Fedora or Mac, it needs to be held - still need to try on Windows), but the initial default should be consistent regardless of when the keyboard was inserted.

#### Steps to reproduce
Boot cpu with keyboard inserted.  Type.  Plug then unplug.  Type again.

**Comment by elbing** [comment]
Does it work without ps/2 adaptor? in afirmative case, does it produce the same effect?

**Comment by gmacd** [comment]
It works in fedora or Mac without the adapter. I haven't been able to test
without the adapter on Harvey.
