### ISSUE TITLE
Gerrit sucks

### ISSUE THREAD

**Issue by rminnich** [Harvey-OS/harvey#46]
#### Expected behavior

Gerrit doesn't suck.

#### Actual behavior

Gerrit sucks.

#### Steps to reproduce

Use Gerrit.

**Comment by sevki** [comment]
this is my favourite bug of all time

**Comment by rminnich** [comment]
We fixed the glitch.

**Comment by linuxbandit** [comment]
@sevki hope you've seen [this one ](https://jira.mongodb.org/browse/PYTHON-532) before jumping to conclusions

But I also love this one as it is very concise
