### ISSUE TITLE
gdbserver on mac in qemu reports 'g' packet reply is too long

### ISSUE THREAD

**Issue by gmacd** [Harvey-OS/harvey#508]
#### Expected behavior
Shouldn't see this message.  I haven't seen it on Linux, connecting to qemu or real hardware.  I build gdb 7.12 for x86_64-elf from source.

#### Actual behavior
See message 'Remote 'g' packet reply too long' after entering 'target remote localhost:1234' in gdb.

#### Steps to reproduce
- Run gdbserver on harvey in qemu on mac
- Connect gdb
- target remote localhost:1234

**Comment by rminnich** [comment]
This is frequently seen when the remote architecture is amd64 and gdb thinks you're a 386. Is this possible? Could you
set arch 386:x86-64

or some such.

**Comment by gmacd** [comment]
The architecture was already set to the same.  Tried explicitly setting it to no effect.  Looking at the packet, it's the same size as the one sent by qemu on Linux (also gdb 7.12).  Makes me think the problem is with the gdb setup on the mac somehow.

**Comment by gmacd** [comment]
Again, this was connecting to qemu's gdb, so not a bug.
