### ISSUE TITLE
Make bootable USB image

### ISSUE THREAD

**Issue by floren** [Harvey-OS/harvey#512]
In Linux:

1. Create a large empty file
2. Partition file: small Linux partition, large Plan 9 partition
3. Format small partition ext2, install extlinux

On Harvey:

1. Subpartition the Plan 9 partition
2. Set up a filesystem (fossil or cwfs)
3. Copy files to the filesystem

The Linux steps could be done once, then the generated 'starter' image could be re-used over and over.

**Comment by hagna** [comment]
I was able to boot partially by following the util/SYSLINUX steps for creating a qcow and then doing  ```qemu-img convert harvey.qcow2 -O raw disk.img``` and burning to usb stick.  Still have to setup a fs on plan 9 partition (/dev/nbd0p2).

**Comment by elbing** [comment]
Feel free of changing what you consider in wiki page about qcow disk with fossil.

**Comment by gmacd** [comment]
I'm going to mark this as done, since it's documented here: https://github.com/Harvey-OS/harvey/wiki/Creating-Harvey-Image

There are issues, which can be addressed specifically.
