### ISSUE TITLE
Can't set breakpoints in gdbserver

### ISSUE THREAD

**Issue by gmacd** [Harvey-OS/harvey#515]
#### Expected behavior
Should be able to connect to a process, set a breakpoint and continue.

#### Actual behavior
Once the breakpoint has been set, if you continue you get an error such as:
Warning:
Cannot insert breakpoint 1.
Cannot access memory at address 0x400cd1

#### Steps to reproduce
- On harvey, run dd, run gdbserver -p <pid>
- On host, run gdb, connect to target, set breakpoint on flsh, continue

**Comment by gmacd** [comment]
Debug from gdb:
Continuing.
Sending packet: $Z0,400cd1,1#9f...Ack
Packet received: 
Packet Z0 (software-breakpoint) is NOT supported
Sending packet: $m400cd1,1#56...Ack
Packet received: 55
Sending packet: $X400cd1,0:#7a...Ack
Packet received: E05
binary downloading supported by target
Sending packet: $X400cd1,1:?#47...Ack
Packet received: E05
Warning:
Cannot insert breakpoint 1.
Cannot access memory at address 0x400cd1

**Comment by floren** [comment]
Here's a diff I used for debugging:

```
diff --git a/sys/src/cmd/gdbserver/debug_core.c b/sys/src/cmd/gdbserver/debug_core.c
index d4bfc639a..b60d8dad6 100644
--- a/sys/src/cmd/gdbserver/debug_core.c
+++ b/sys/src/cmd/gdbserver/debug_core.c
@@ -69,9 +69,14 @@ arch_set_breakpoint(struct state *ks, struct bkpt *bpt)
        char *err;
 
        err = rmem(bpt->saved_instr, ks->threadid, bpt->bpt_addr, bpsize);
-       if (err)
+       if (err) {
+               fprint(2, "rmem failed: %s\n", err);
                return err;
+       }
        err = wmem(bpt->bpt_addr, ks->threadid, breakpoint, bpsize);
+       if (err) {
+               fprint(2, "wmem failed: %s\n", err);
+       }
        return err;
 }
 
@@ -104,7 +109,7 @@ dbg_activate_sw_breakpoints(struct state *ks)
                error = arch_set_breakpoint(ks, &breakpoints[i]);
                if (error) {
                        ret = error;
-                       fprint(2, "BP install failed: %lx", breakpoints[i].bpt_addr);
+                       fprint(2, "BP install failed: %lx: %s", breakpoints[i].bpt_addr, error);
                        continue;
                }
 
diff --git a/sys/src/cmd/gdbserver/gdbstub.c b/sys/src/cmd/gdbserver/gdbstub.c
index b18c1d406..81c0abb36 100644
--- a/sys/src/cmd/gdbserver/gdbstub.c
+++ b/sys/src/cmd/gdbserver/gdbstub.c
@@ -736,7 +736,9 @@ gdb_cmd_break(struct state *ks)
        unsigned long length;
        char *error = nil;
 
-       if (*bpt_type >= '0') {
+       print("got a breakpoint request\n");
+       if (*bpt_type >= '1') {
+               print("bad type %c, returning\n", *bpt_type);
                return;
        }
 
@@ -745,17 +747,20 @@ gdb_cmd_break(struct state *ks)
                return;
        }
        if (!hex2long(&ptr, &addr)) {
+               print("bad addr\n");
                error_packet(remcom_out_buffer, Einval);
                return;
        }
        if (*(ptr++) != ',' || !hex2long(&ptr, &length)) {
+               print("bad length\n");
                error_packet(remcom_out_buffer, Einval);
                return;
        }
 
-       if (remcom_in_buffer[0] == 'Z' && *bpt_type == '0')
+       if (remcom_in_buffer[0] == 'Z' && *bpt_type == '0') {
+               print("setting breakpoint %p\n", addr);
                error = dbg_set_sw_break(ks, addr);
-       else if (remcom_in_buffer[0] == 'z' && *bpt_type == '0')
+       } else if (remcom_in_buffer[0] == 'z' && *bpt_type == '0')
                error = dbg_remove_sw_break(ks, addr);
 
        if (error == 0)
```

The important change is at line 736, where I go from checking bpt_type >= 0 to >= 1. Type 0 is software breakpoint, which is what we want. 

After compiling with this, I see the following error:

```
Connected
got a breakpoint request
setting breakpoint 401cc9
wmem failed: 05bad process or channel control request
BP install failed: 401cc9: 05bad process or channel control requestcpu%
```

It's a problem with the wmem() function, although I have not figured out how yet.

**Comment by floren** [comment]
If I `stop dd | rc` first, I get this error instead:

```
got a breakpoint request
setting breakpoint 401af4
wmem failed: 05fixfault: write on read-only

BP install failed: 401af4: 05fixfault: write on read-only
```

**Comment by gmacd** [comment]
This matches what I've been seeing.

**Comment by gmacd** [comment]
(I put this in slack by mistake - repeating here for the record)

`cat /proc/pid/segment` shows that the 2nd segment of dd is read-only - this contains the address of the breakpoint.

**Comment by gmacd** [comment]
The key code in acid seems to be the sproc() function.  There seems to be some process mapping done by calling attachproc when it's attached to a pid.  I don't quite understand it yet, but it seems key.

**Comment by gmacd** [comment]
Looks like acid only sets breakpoints when the process has stopped.  You can see this in sys/lib/acid/port:bpset.  It waits for the process to stop before adding the breakpoint.  The acid manual gives the same reason we've discovered - you can't write to /proc/pid/mem unless the process has stopped.

**Comment by floren** [comment]
Ok; so it seems like we just need to fix writing to mem. The kernel seems to be sensibly against other processes messing with the text segment; what do we need to do to be able to write to it, though?

**Comment by gmacd** [comment]
Yeah, I suspect this is where attachproc() comes in.  It seems to be creating a new map and overlaying the process text over the existing text?  If this is what's happening, I guess the segment would be writable, otherwise what's the point?

I may be off the mark completely here, but it seems plausible.  I haven't had a chance to verify it yet, and won't be able to look at it any further tonight :(

**Comment by gmacd** [comment]
Updating from slack yesterday...

It's failing at fault.c:212:
```        if((s->type & SG_WRITE) == 0)
            error("fixfault: write on read-only\n");```
Which matches what we've seen in the log.  s->type=88 at this point.

And this matches the perms I saw in /proc/pid/segment.

This check was added as part of this commit: https://github.com/Harvey-OS/harvey/commit/121208f9f0ea72e52c87021c4acb5d7ad51e9c37

Not sure why I didn't check the history of this file before....  Anyway, I'm done for tonight.  If anyone wants to pick this up feel free, otherwise I'll pick it up again tomorrow night.

**Comment by gmacd** [comment]
So what is best here?  I can delete this code, set the breakpoint and continue (locally).  I haven't managed to stop properly yet.

Regarding this particular piece of code though, the check for SG_WRITE didn't seem to exist originally, but it seems sensible.  So is it better to change the permissions on the segment when creating it?

**Comment by rminnich** [comment]
you mean change permissions on the segment so you're putting a breakpoint in every process using this code :-)
nah :-)
you need to go look at how original 9 does it. We probably screwed up when we did the move to ELF.

**Comment by gmacd** [comment]
In the code I've reimplemented from acid, when it attaches, it calls loadmap to create a new map with new segments for text and data.  I suspect it's here I need to ensure the segment is writable.

But I need to verify that.

**Comment by gmacd** [comment]
In addition to the change from SG_RONLY -> SG_READ and SG_WRITE potentially causing problems, we also need to look at the addition of SG_LOAD.  This seems to be intended to replace SG_TEXT, but only seems to have been partially applied.  I think we need to add this check to devproc.c:procctlmemio, otherwise txt2data doesn't get called when writing the breakpoint.

Changing this pushes the problem slightly further along - I'm now reaching the permissions failure code in fault.c:fault, probably because I still don't have the segments set up quite right.

**Comment by gmacd** [comment]
TBH, these problems with the segment flags probably deserve their own issue.

**Comment by gmacd** [comment]
Still need to replace the instruction and ensure we can continue after hitting the breakpoint.

**Comment by gmacd** [comment]
Nearly there - can set a breakpoint, hit it and continue, but it doesn't get activated again.  Once that's done, I think we can close this and look at the other issues.

**Comment by gmacd** [comment]
When we continue after hitting a breakpoint, gdb sends a 's' instruction to single step.  We don't really implement this yet - we treat it as a continue.

This seems to be done using machdata->foll() elsewhere.
