### ISSUE TITLE
SHA1

### ISSUE THREAD

**Issue by elbing** [Harvey-OS/harvey#516]
Recently libsec was updated, it's needed the upgrade of the kernel and related to new cryptography improvements.

**Comment by sevki** [comment]
I'm guessing this is related to the [SHATTERED](http://shattered.io/)

what's the impact of this in the kernel? 
does it need to be replaced with something else? (if so, what? SHA256 or SHA512?)

**Comment by elbing** [comment]
At least devcap and factotum. Both should be 512. Maybe other related. We need to improve it in the kernel for seeing the scope. Works were stopped due to blocking issues.

**Comment by rminnich** [comment]
We used sha256 on the recommendation of eric grosse, former security VP of google, now retired, who had a lot to do with the design of all this code. You ought to consider using the sha256 I put into akaros, at eric's recommendation, as it is used in ChromeOS and widely considered to be a very good implementation.

**Comment by rminnich** [comment]
changing to sha256 was really easy. None of this is all that hard, it's not a bad newbie project.

**Comment by gmacd** [comment]
Spring cleaning - closing old issues
