### ISSUE TITLE
gdbserver backtrace doesn't work

### ISSUE THREAD

**Issue by gmacd** [Harvey-OS/harvey#544]
gdbserver log indicates it can't translate the address:

10.0.2.15 Apr 22 04:05:13 packet :m7fffffdffe40,40:
10.0.2.15 Apr 22 04:05:13 rmem(736030, 92, 7fffffdffe40, 64)
10.0.2.15 Apr 22 04:05:13 get1 failed: can't translate address 7fffffdffe40
10.0.2.15 Apr 22 04:05:13 gdb_cmd_memread: can't translate address 7fffffdffe40
10.0.2.15 Apr 22 04:05:13 RETURN :E05:

**Comment by gmacd** [comment]
So looks like the stack segment isn't mapped?  So maybe need to change wmem/rmem when accessing the stack...  TBC.

**Comment by rminnich** [comment]
stack segment has to be mapped or acid could never have worked. Looks like another bug.

**Comment by gmacd** [comment]
/proc/pid/segment format had changed.  Fixed.
