### ISSUE TITLE
Go port on harvey

### ISSUE THREAD

**Issue by rurtle** [Harvey-OS/harvey#584]
Currently, the Go port on Harvey is not a first class port. We need to address the following -

For now, we build Go by setting GOOS=plan9. Necessary changes have to be made so that we can use GOOS=harvey instead. Efforts should be made so GOOS=harvey should imply GOOS=plan9. This should in line with the way GOOS=android "implies" linux.

**Comment by rminnich** [comment]
we're closing this. With plan 9 a.out support, we have go on Plan 9. There will likely never be a real Harvey port but that does not matter.
