### ISSUE TITLE
Full name resolve for build tool

### ISSUE THREAD

**Issue by grd** [Harvey-OS/harvey#63]
#### Expected behavior
/path/to/fs.c: In function ‘keylist’:
/path/to/fs.c:471:14: warning: unused variable ‘zero’ [-Wunused-variable]
  static char zero[Nearend];

#### Actual behavior
fs.c: In function ‘keylist’:
fs.c:471:14: warning: unused variable ‘zero’ [-Wunused-variable]
  static char zero[Nearend];

This is quite annoying when there are multiple fs.c files that you have to locate and try out. I discovered that GCC uses the path that is given as input, see https://stackoverflow.com/questions/1282392/can-gcc-be-configured-to-not-print-out-a-full-path-in-warning-error-messages

The solution would be to resolve the complete path of the compiled source file in the build program.

**Comment by grd** [comment]
If someone can point out where the source of the build program is then I can try a hack to solve this.

**Comment by elbing** [comment]
sys/src/cmd/factotum

**Comment by rminnich** [comment]
Thanks for the offer of help. We're hoping to kill the current build program soon-ish so it would be even better if you could help us make the new one work :-) Interested?

**Comment by grd** [comment]
Let me deal with the warnings first. But who knows. I think we can close this issue.
