### ISSUE TITLE
Contributing page is incomplete

### ISSUE THREAD

**Issue by grd** [Harvey-OS/harvey#66]
Before the section "push the changes to your new remote" there needs to be a section "git remote set-url USER_NAME https://github.com/grd/harvey.git"

**Comment by grd** [comment]
Adding to that, the "It's time to fork the repo!", is that done only once or does that count for every contribution? What I am saying is that "hub" isn't well known and also not well documented. And I am having troubles with synchronizing after contribution. My knowledge of "git" is average.

**Comment by elbing** [comment]
You will fork only once. Rest of future times you will do only:
git remote add YOUR_USER git://github.com/YOUR_USER/harvey.git
git push YOUR_USER feature
hub pull-request

What kind of troubles with synchronizing are you having?

hub tool is something new to me too, we're all learning everyday new things, which is one of the main goals in Harvey, but in it's github site there's some useful information. Think in it just in a wrapper to git, you could do the same it does through a bunch of usual git commands, hub is there only to make life easier.

**Comment by grd** [comment]
Thanks for the clarification! The problem I have with synchronizing is that when I do a "git pull" it says that my branch is x commits ahead of master.

**Comment by elbing** [comment]
If you're working into a branch and is outdated respect master, just do a _git pull --rebase_. This will put your changes after the pull. In case there would be conflicts, you will have to solve them manually, but they are marked with something like ">>>>>HEAD" and git will tell you about what files are them.

**Comment by grd** [comment]
Thanks! I think btw that documenting this would clarify it a lot. Shall I give it a try?

**Comment by elbing** [comment]
Yes, of course. Just send a pull-request to CONTRIBUTING.md file completing all you think is missing as a new experience programmer here :-).

**Comment by grd** [comment]
I will do that this evening. More input is welcome btw ;-)

**Comment by grd** [comment]
Okay, now I am having troubles with `hub pull-request` itself. My `git remote -v` states:

`grd	https://github.com/grd/harvey.git (fetch)`
`grd	https://github.com/grd/harvey.git (push)`
`origin	https://github.com/Harvey-OS/harvey.git (fetch)`
`origin	https://github.com/Harvey-OS/harvey.git (push)`

I pushed branch `issue_66` with `git push grd issue_66` and after that I did `hub pull-request`. The answer is:

`Error creating pull request: Unprocessable Entity (HTTP 422)`
`No commits between Harvey-OS:master and grd:issue_66`

Help...

**Comment by elbing** [comment]
Seems like if you have unpushed changes... did you "git commit" all?
If it keeps happening, set the `HUB_VERBOSE=1 hub pull-request` to see if it says something more useful. All bugs related in hub tool are old.
