### ISSUE TITLE
The Harvey wiki has imprecise references around networking

### ISSUE THREAD

**Issue by froztbyte** [Harvey-OS/harvey#694]
#### Expected behavior

The section https://github.com/Harvey-OS/harvey/wiki/Getting-Started#running-harvey refers to a "class C network". While this is at least technically correct, it is quite likely imprecise use and should be removed.

It is my belief that the author was referring to the subnet size, and that (should this belief be accurate) the author is mistaken. In this case, please refer to RFC1519 which has superceded the RFC791 definition for a number of decades.

In the alternate case, please update the document to be clearer about this usage.

Further information or detail may be gleaned in the links below:
- https://en.wikipedia.org/wiki/Classful_network
- https://networkengineering.stackexchange.com/a/6502

#### Steps to reproduce
- click links
- read
- ???
- profit!

</details>

**Comment by elbing** [comment]
Fixed, thanks.
