### ISSUE TITLE
AHCI driver broken

### ISSUE THREAD

**Issue by elbing** [Harvey-OS/harvey#7]
Please, see in our Google group last state of this issue.

**Comment by rminnich** [comment]
I suspect that the STD fix have help here. I just tried a few things and things are working far better than in the past.

**Comment by rminnich** [comment]
Can you tell us how to test if this is fixed?

**Comment by elbing** [comment]
I usually make a qcow disk. Compiling fdisk/prep using p9p yacc to avoid weird bison errors. After that boot kvm with ahci disk (I think in "preparing disk" topic in group list is the exact command line) and use fdisk/prep.

**Comment by elbing** [comment]
Driver is working.
