### ISSUE TITLE
Stats commits suicide on right mouse click

### ISSUE THREAD

**Issue by myk321** [Harvey-OS/harvey#70]
#### Expected behavior
stats does not fail when stats window clicked on with right mouse button

#### Actual behavior
stats quits and displays something like the following in the rio window
stats 90: suicide: sys: trap: fault write addr=0x41fd60 pc=0x4169fc 

#### Steps to reproduce
Approach 1:
- Start harvey / rio, create 2 windows:
- Create window #1
- Run 'stats' in window #1
- Create window #2
- After creating window #2, right mouse button click on the stats window #1
- Error is displayed
Can continue to recreate the error:  Create new stats windows (#3 etc).  Put focus on another window and then right click on stats window (#3 etc.).  Same error is generated again.

Approach 2
- Start harvey / rio, create 1 windows:
- Run 'stats' in window #1
- Left mouse button click on the rio background
- Right mouse button click on stats window (#1)

#### QEMU output
init: starting /bin/rc
10.0.2.15 Feb 26 18:44:16 starting dns resolver on 10.0.2.15's /net
machp access spllo, stack: k:13f4cf k:138864 k:19cb35 k:11a7d3 k:1de3d7 k:1de621 k:148db8 k:139695
vbecall: sizeof u is 76
vbecall: sizeof u is 76
vbecall: sizeof u is 76
machp access spllo, stack: k:13f4cf k:138864 k:142638 k:1221f5 k:163892 k:121402 k:11b09c k:11b3be k:1de7b3 k:1de9f4 k:148db8 k:139695
machp access spllo, stack: k:13f4cf k:138864 k:19cabf k:19c82b k:121380 k:11ae09 k:11b3be k:1de7b3 k:1de9f4 k:148db8 k:139695
machp access spllo, stack: k:13f4cf k:138864 k:19caea k:1a4b00 k:1a464f k:1de7b3 k:1de9f4 k:148db8 k:139695
machp access spllo, stack: k:13f4cf k:138864 k:1a48c5 k:1de7b3 k:1de9f4 k:148db8 k:139695
machp access spllo, stack: k:13f4cf k:138864 k:1a4a61 k:1a49dc k:1de7b3 k:1de9f4 k:148db8 k:139695
machp access spllo, stack: k:13f4cf k:138864 k:13d69f k:194f81 k:193dc7 k:1de3d7 k:1de621 k:148db8 k:139695
write fault fail Load(r-x) pid 90 addr 0x41fd60 pc 0x4169fc

**Comment by elbing** [comment]
You can look at where it's failing doing:
    objdump -S stats
An look for in a text editor for 0x4169fc address. And see in what function it is.

Thanks for reporting. We'll invest it.

**Comment by keedon** [comment]
Blowing up in memmove

**Comment by keedon** [comment]
Patch to prevent trying to write to read-only memory has fixed this

**Comment by myk321** [comment]
Patch works great - thank-you!

**Comment by elbing** [comment]
Now suicides running it with flags (`stats -lmisce`):

        p.x += Labspace;
        maxy = p.y+dy;
        maxw = 0;
        r[1] = '\0';
        for(s=text; *s; ){
  4006ea:       48 8b 45 f8             mov    -0x8(%rbp),%rax
  **4006ee:       0f b6 00                movzbl (%rax),%eax**

**Comment by rminnich** [comment]
with one flag? two flags?  Does it take a certain number?

**Comment by keedon** [comment]
Patch merged
