### ISSUE TITLE
386\bin\aux folder on Windows

### ISSUE THREAD

**Issue by SebastianRuan** [Harvey-OS/harvey#808]
I attempted to clone the repository to my Windows computer but was met with the error: "cannot create directory at '386/bin/aux': Invalid argument". Turns out Windows has reserved folder names and "./aux" is one of them. It might be a good idea to change the name of this folder to make it easier for windows users to clone the repo.

**Comment by elbing** [comment]
Did you follow the wiki? Are you trying with cygwin or mingw32? Last both weren't tested. Building on windows is for Windows 10 linux subsystem.

**Comment by SebastianRuan** [comment]
I didn't get that far. I can't seem to clone the entire repository. I tried to clone through the Windows 10 Linux subsystem which has fixed my "/aux" problem, but it still seems that Windows doesn't like some other file names: 

```
git clone https://github.com/Harvey-OS/harvey.git
Cloning into 'harvey'...
remote: Counting objects: 112538, done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 112538 (delta 26), reused 26 (delta 14), pack-reused 112482
Receiving objects: 100% (112538/112538), 124.74 MiB | 11.88 MiB/s, done.
Resolving deltas: 100% (83388/83388), done.
Checking connectivity... done.
error: unable to create file rc/bin/9fat: (Invalid argument)
error: unable to create file rc/bin/a: (Invalid argument)
error: unable to create file rc/bin/b: (Invalid argument)
error: unable to create file rc/bin/c: (Invalid argument)
error: unable to create file rc/bin/usbfat: (Invalid argument)
Checking out files: 100% (12055/12055), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

Is it possible to escape the file names while cloning? For example: "rc/bin/9fat\:"

**Comment by elbing** [comment]
Seems that during the cleaning process in january we forgot to remove some old scripts. They're obsolete and unused. We don't check windows builds by default so this issue didn't rise til now. Let me review /rc dir in a PR referring this issue and when it's done I'll write here for some feedback if you can.
Thanks!

**Comment by elbing** [comment]
Also, could you ensure that the ubuntu packages of the subsystem are updated?

**Comment by SebastianRuan** [comment]
I updated my system packages and re-cloned the repository, but still received the 'invalid arguments' error. But as you say, I don't need those files so I'll take a look at what I can do now. Thanks for looking into the issue.

**Comment by gmacd** [comment]
Spring cleaning - closing old issues
