### ISSUE TITLE
Request: Provide an IRC channel

### ISSUE THREAD

**Issue by dertuxmalwieder** [Harvey-OS/harvey#831]
As IRC is the de-facto standard communication channel for many open-source projects and Slack is rather limiting (in fact, the only thing it does better than IRC is displaying conversations), I would like to request an official IRC channel, e.g. on Freenode, as an alternative to the Slack channels.

**Comment by sevki** [comment]
You are right, in an ideal world we'd be on IRC, and we have experimented with, at some point there was a #harvey on freenode, furthermore I don't think anyone of us on the core team is a huge fan of slack, that being said it is super convenient. 

We are exploring alternative means of communication but right now we do not have the resources to switch to another medium I'm afraid.

**Comment by dertuxmalwieder** [comment]
You wouldn't have to switch, I guess. There are still gateways.

* https://github.com/insomniacslk/irc-slack
* https://www.reddit.com/r/Slack/comments/8hyky9/best_alternative_to_the_now_defunct_irc_gateway/

**Comment by sevki** [comment]
I'm not quite sure what you are suggesting here but you are certainly welcome to use an IRC gateway to connect to slack if that's what you like
