### ISSUE TITLE
Remove deprecated/unmaintained code

### ISSUE THREAD

**Issue by Shamar** [Harvey-OS/harvey#9]
We should remove all code that we are not going to maintain.

For example, are we going to include abaco in Harvey? What about libhtml?

**Comment by Shamar** [comment]
Turns out that libhtml is used by abaco and htmlfmt.
I think we can get rid of both.

**Comment by rminnich** [comment]
Can we close this issue now?

**Comment by Shamar** [comment]
No, we still have code to remove.

Are we going to maintain Abaco, for example?
What about games? Acid? Acme?

We should really remove from the main repo everything we are not going to support. 

Some tools can be moved to different repos (games?), but code removed is code debugged. 
And a lot of code that we do not even compile, pollute our grep search, for example.

On the flip side, we should list somwhere the code that we need but is not yet included by the build. While working on #5, it took to me a while to realize that we where missing devcap, devssl and exportfs.

**Comment by Shamar** [comment]
We are moving some valuable tools to [Harvey-OS/legends](https://github.com/Harvey-OS/legends) (see #20 for a list)

**Comment by rminnich** [comment]
Are we about done this bug?

**Comment by Shamar** [comment]
I don't think so... games are still there (but they could become actual if we get drawterm working), but what about /dist/replica? What about /sys/src/cmd/db or cmd/cec...

I think this issue will last till the first stable release of Harvey's installation CD.

I'm happy to move or remove obsolete software, but what we need to progress on this front is a comprehensive list of libraries and tools to keep and remove.

**Comment by elbing** [comment]
Mostly dead code removed. Some little remaining things don't justify to keep this issue open.
