### ISSUE TITLE
Issue with syslinux on macOS

### ISSUE THREAD

**Issue by G3bE** [Harvey-OS/harvey#910]
#### Expected behaviour
syslinux creates a proper `harvey.raw` file
#### Actual behavior
It gives the following output:
```
Formatting 'harvey.raw', fmt=raw size=3221225472
chgrp: nikolas: illegal group name
2020/02/01 22:32:00 /usr/bin/chgrp nikolas harvey.raw: exit status 1
2020/02/01 22:32:00 Detaching
2020/02/01 22:32:00 exit status 1
2020/02/01 22:32:00 exit status 1
```
Note: My username is `nikolas`
#### Steps to reproduce
- Get MacOS 10.15.2
- Download and build harvey
- Follow the steps on creating a USB Image [here](https://github.com/Harvey-OS/harvey/wiki/Creating-Harvey-Image)

**Comment by elbing** [comment]
Create the group nikolas manually. I’ll update the wiki.

**Comment by G3bE** [comment]
Getting this now:
```
Formatting 'harvey.raw', fmt=raw size=3221225472
2020/02/02 16:19:18 modprobe nbd max_part=63: exec: "modprobe": executable file not found in $PATH
2020/02/02 16:19:18 Detaching
2020/02/02 16:19:18 exit status 1
2020/02/02 16:19:18 exit status 1
```
I looked into the source file for syslinux and those are the commands not available on MacOS:
```
modprobe
sfdisk
mkfs.ext4
extlinux
```

**Comment by elbing** [comment]
Well, all of those are there for loading qemu-nbd (network block device) driver for mounting the virtual qcow2 image. I don’t know if it’s even possible in Mac and we didn’t thought in it at the time that howto was written.
That won’t work on BSD too, so try to read what the script does and try to translate it to something that can be done in Mac.
Sorry for the inconvenience.

**Comment by G3bE** [comment]
Looks like it is as simple as creating a disk and writing mbr.sys harvey.32bit and the syslinux stuff in it. Should be doable, thanks for the help ^^
