### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by phil6809** [Harvey-OS/harvey#911]
#### Expected behavior
Not to fail.
#### Actual behavior
Failed.
 GO111MODULE=on GOBIN="$(pwd)/util" go get ./util/src/harvey/cmd/...

package golang.org/x/crypto/ssh/terminal
        imports golang.org/x/sys/unix
        imports math/bits: unrecognized import path "math/bits"

#### Steps to reproduce
- 
- 
- 

#### QEMU output
<details>
```
<your output here>
```
</details>

**Comment by elbing** [comment]
It seems to work:

```
$ GO111MODULE=on GOBIN="$(pwd)/util" go get ./util/src/harvey/cmd/...
$
```

Also `bootstrap.sh` worked well with Go 1.13.6 ¿?

```
$ freebsd-version -kru
12.1-RELEASE-p1
12.1-RELEASE-p1
12.1-RELEASE-p1
```
What OS did you use?

**Comment by phil6809** [comment]
Slackware Linux,
go v1.1.2

**Comment by elbing** [comment]
`math/bits` was added in Go 1.9. Upgrade it or skip `util/src/harvey/cmd/telnet` which in fact is old and useless since the console was back at kernel and properly set and depends on a `listen1`commented line in `cpurc`.

I encourage you upgrading Go better.

**Comment by phil6809** [comment]
Thanks, that fixed that problem,  and have compiled all the binaries,.
I only installed go as your build system depended on it.
The next problem is ninep does not compile and I guess it is the same reason .

 I have my own u9fs server for 9front, so I may persist and investigate further or I may just continue with 9front.

Overall This is too much effort for me, and I probably will wait for you to distribute an ISO file like other 9 variants.

Presently , the only feature of harveyos  that I know is modern, is the build system dependency hell that is prevalent with all modern software.

Thanks for your time.
