### ISSUE TITLE
Support inferno's Dis Machine And Binary.

### ISSUE THREAD

**Issue by keito940** [Harvey-OS/harvey#915]
Plz.

**Comment by elbing** [comment]
We removed aout binary support at the begining, after a debate if we should burn the bridges and move onto elf. I'm afraid it would be a big rework including in the kernel aout support again.
Maybe through [APEX](https://github.com/Harvey-OS/apex) you could build with some hack a working version of Inferno as if it was over linux, though APEX hasn't POSIX threads support yet. It's a similar problem with the Plan 9 Go port that Ron hacked for making it to work on Harvey getting around the differences.

**Comment by rminnich** [comment]
a.out support is back, please test dis and its binaries.

**Comment by sevki** [comment]
@keito940 :point_up: :tada:

**Comment by sevki** [comment]
Closing this, as this was more of a feature request than an issue. New issues should be opened on the basis of whether or not this is working properly with QEMU outputs and steps to reproduce.
