### ISSUE TITLE
Go apps crashing 

### ISSUE THREAD

**Issue by sevki** [Harvey-OS/harvey#929]
reported by @elbing, reproduced by @fuchicar 
```
cpu% cd src/hello
Can't cd src/hello: 'src/hello' does not exist
cpu% cd src
cpu% ls -l
d-rwxr-xr-x M 82 harvey harvey 4 Jul  6 06:54 hellogo
cpu% cd hellogo
cpu% ./hellogo
hellogo 4038: suicide: sys: trap: fault read addr=0x0 pc=0x2582f9
```

**Comment by fuchicar** [comment]
forkp.out doesn't work either. I'm going to check at what point "helloworld" stopped working

**Comment by sevki** [comment]
smart money is on this PR https://github.com/Harvey-OS/harvey/pull/924

**Comment by fuchicar** [comment]
Yes, PR # 924 breaks the compatibility with plan9 binaries

**Comment by fuchicar** [comment]
It works again in #930
