### ISSUE TITLE
harvey consistently hangs for couple seconds after `Rread` to transmit new fcalls

### ISSUE THREAD

**Issue by sevki** [Harvey-OS/harvey#959]
whilst booting Harvey transmits couple of `Rread` and waits couple of seconds before transmitting new fcalls

Calls are always 
```
Rread(offset=0, count=64)
Rread(offset=0, count=64)
Rread(offset=64, count=168)
```
than it hangs... for a couple of seconds 

here are some examples

here harvey is trying to read `harvey/amd64/bin/date`
![image](https://user-images.githubusercontent.com/429977/89110167-e3513680-d43f-11ea-9864-6870c49adc73.png)
here is the same view expanded
![image](https://user-images.githubusercontent.com/429977/89110232-9ae64880-d440-11ea-8b52-f042c1e6233f.png)
same exact pattern harvey trying to read `harvey/amd64/bin/rc`
![image](https://user-images.githubusercontent.com/429977/89110248-c10be880-d440-11ea-9afa-178d06444a8b.png)
trying to read `harvey/amd64/bin/mntgen`
![image](https://user-images.githubusercontent.com/429977/89110265-f7e1fe80-d440-11ea-8658-9bc5ee2e6843.png)

**Comment by rminnich** [comment]
IIRC this was on qemu, right? not real hardware. If so we should close it, these measurements on qemu are misleading.

**Comment by fhs** [comment]
I'm also seeing really slow read speed. I suspect its a driver issue because I'm seeing the same slow read speed with HTTP. Write speed is fine, but reads are super *slow*:
```
cpu% time dd -if /dev/zero -of big.bin -bs 8192 -count 10000
10000+0 records in
10000+0 records out
0.00u 2.70s 6.64r 	 dd -if /dev/zero -of big.bin ...
cpu% time dd -if /dev/zero -of 4mb.bin -bs 8192 -count 500
500+0 records in
500+0 records out
0.00u 0.20s 0.33r 	 dd -if /dev/zero -of 4mb.bin ...
cpu% time dd -if 4mb.bin -of /dev/null -bs 8192
500+0 records in
500+0 records out
0.01u 0.20s 46.18r 	 dd -if 4mb.bin -of /dev/null ...
cpu% time hget http://10.0.2.2:8000/usr/harvey/4mb.bin >/dev/null
0.07u 0.05s 74.35r 	 hget http://10.0.2.2:8000/usr/harvey/4mb.bin
```
(I'm testing this with [u9fs](https://github.com/sevki/u9fs) because I originally suspected ufs bug, and using [webfsd](https://linux.bytesex.org/misc/webfs.html) for web server.)

**Comment by sevki** [comment]
@rminnich even if this is a qemu only issue, (I'm not sure if we ever verified that), a significant amount of development is done on qemu. so I still think this is worth keeping around and fixing

**Comment by fhs** [comment]
It seems like the issue is with qemu user-mode networking. I'm not seeing the slow reads after switching to bridge networking on qemu.
